using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using DevExpress.Mvvm.DataAnnotations;

namespace TreeListDemo {
    [MetadataType(typeof(DataAnnotationsElement2Metadata))]
    public class DataAnnotationsElement2_FluentAPI {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Employer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get { return FirstName + " " + LastName; } }
        public Gender Gender { get; set; }
        public int Age { get; set; }
        public string SSN { get; set; }

        public override string ToString() {
            return "Attribute support (Fluent API)";
        }
    }

    public class DataAnnotationsElement2Metadata : IMetadataProvider<DataAnnotationsElement2_FluentAPI> {
        void IMetadataProvider<DataAnnotationsElement2_FluentAPI>.BuildMetadata(MetadataBuilder<DataAnnotationsElement2_FluentAPI> builder) {
            builder.Property(p => p.ID).NotAutoGenerated();
            builder.Property(p => p.ParentID).NotAutoGenerated();
            builder.Property(p => p.Employer).NotEditable();
            builder.Property(p => p.FirstName).DisplayName("First name").Required();
            builder.Property(p => p.LastName).DisplayName("Last name").Required();
            builder.Property(p => p.FullName).DisplayName("Full name");
            
            builder.Property(p => p.SSN).ReadOnly();
        }
    }
}
