Imports DevExpress.Mvvm.DataAnnotations
Imports DevExpress.Mvvm.POCO
Imports DevExpress.Utils
Imports DevExpress.Xpf.Charts.Heatmap
Imports DevExpress.Xpf.DemoBase
Imports System
Imports System.Windows.Media.Imaging

Namespace TreeMapDemo

    <CodeFile("Modules/Heatmap/ColorProviders.xaml")>
    <CodeFile("Modules/Heatmap/ColorProviders.xaml.(cs)")>
    <NoAutogeneratedCodeFiles>
    Public Partial Class ColorProviders
        Inherits TreeMapDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Public Class ColorProviderInfo

        Public Property Name As String

        Public Property ColorProvider As HeatmapColorProviderBase

        Public Overrides Function ToString() As String
            Return Name
        End Function
    End Class

    <POCOViewModel>
    Public Class ColorProvidersDemoViewModel

        Public Shared Function Create() As ColorProvidersDemoViewModel
            Return ViewModelSource.Create(Function() New ColorProvidersDemoViewModel())
        End Function

        Public Overridable Property XArguments As Integer()

        Public Overridable Property YArguments As Integer()

        Public Overridable Property Values As Double(,)

        Protected Sub New()
            Dim uri As Uri = AssemblyHelper.GetResourceUri(GetType(ColorProviders).Assembly, "/Data/Heightmap.jpg")
            Dim image As BitmapImage = New BitmapImage(uri)
            Dim matrix As Double(,) = New Double(image.PixelHeight - 1, image.PixelWidth - 1) {}
            Dim stride As Integer = image.PixelWidth * 4
            Dim size As Integer = image.PixelHeight * stride
            Dim pixels As Byte() = New Byte(size - 1) {}
            image.CopyPixels(pixels, stride, 0)
            For i As Integer = 0 To image.PixelHeight - 1
                For j As Integer = 0 To image.PixelWidth - 1
                    matrix(i, j) = BitConverter.ToInt32(pixels, i * stride + 4 * j)
                Next
            Next

            XArguments = HeatmapDataSourceGenerator.GetArray(image.PixelWidth)
            YArguments = HeatmapDataSourceGenerator.GetArray(image.PixelHeight)
            Values = matrix
        End Sub
    End Class
End Namespace
