Imports DevExpress.Xpf.DemoBase

Namespace TreeMapDemo

    <CodeFile("Modules/Heatmap/EmptyCells.xaml")>
    <CodeFile("Modules/Heatmap/EmptyCells.xaml.(cs)")>
    <NoAutogeneratedCodeFiles>
    Public Partial Class EmptyCells
        Inherits TreeMapDemoModule

        Public Sub New()
            InitializeComponent()
            DataContext = CreateDataSet("/Data/SalesPersons.xml")
        End Sub
    End Class
End Namespace
