Imports DevExpress.Xpf.DemoBase

Namespace TreeMapDemo

    <CodeFile("Modules/Heatmap/Labels.xaml")>
    <CodeFile("Modules/Heatmap/Labels.xaml.(cs)")>
    <NoAutogeneratedCodeFiles>
    Public Partial Class Labels
        Inherits TreeMapDemoModule

        Public Sub New()
            InitializeComponent()
            DataContext = CreateDataSet("/Data/BalanceOfTrade.xml")
        End Sub
    End Class
End Namespace
