Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/AgendaViewDemoModule.xaml", "ViewModels/ViewTypes/AgendaViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class AgendaViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
