Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/DayViewDemoModule.xaml", "ViewModels/ViewTypes/DayViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class DayViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
