Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/ListViewDemoModule.xaml", "ViewModels/ViewTypes/ListViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class ListViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
