Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/OneMonthViewDemoModule.xaml", "ViewModels/ViewTypes/OneMonthViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class OneMonthViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
