Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/WeekViewDemoModule.xaml", "ViewModels/ViewTypes/WeekViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class WeekViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
