Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ViewTypes/WorkWeekViewDemoModule.xaml", "ViewModels/ViewTypes/WorkWeekViewDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class WorkWeekViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
