Imports System.Windows
Imports DevExpress.Xpf.Core.Native
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/DataAggregation/DataAggregation.xaml"), CodeFile("Modules/DataBinding/DataAggregation/DataAggregation.xaml.(cs)"), CodeFile("DataModels/DevAVSalesData.(cs)"), CodeFile("DataModels/DateTimeArgumentData.(cs)"), CodeFile("DataModels/NumericArgumentData.(cs)"), CodeFile("Modules/DataBinding/DataAggregation/DateTimeDataAggregationTab.xaml"), CodeFile("Modules/DataBinding/DataAggregation/DateTimeDataAggregationTab.xaml.(cs)"), CodeFile("Modules/DataBinding/DataAggregation/NumericDataAggregationTab.xaml"), CodeFile("Modules/DataBinding/DataAggregation/NumericDataAggregationTab.xaml.(cs)"), CodeFile("Modules/DataBinding/DataAggregation/QualitativeDataAggregationTab.xaml"), CodeFile("Modules/DataBinding/DataAggregation/QualitativeDataAggregationTab.xaml.(cs)"), CodeFile("Modules/DataBinding/DataAggregation/TimeSpanDataAggregationTab.xaml"), CodeFile("Modules/DataBinding/DataAggregation/TimeSpanDataAggregationTab.xaml.(cs)"), CodeFile("Modules/DataBinding/StandardDeviationCustomAggregateFunction.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class DataAggregationDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub OnTabItemLoaded(ByVal sender As Object, ByVal e As RoutedEventArgs)
            Dim tabbedViewModel As NotCachedTabbedModuleViewModel = CType(DataContext, NotCachedTabbedModuleViewModel)
            Dim [module] As TabItemModule = CType(LayoutHelper.FindElementByType(Me, sender.GetType()), TabItemModule)
            tabbedViewModel.Options = [module].Options
        End Sub
    End Class
End Namespace
