Imports System
Imports System.Globalization
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/SeriesTypes/Financial/FinancialSeriesDemo.xaml"), CodeFile("Modules/SeriesTypes/Financial/StockTab.xaml"), CodeFile("Modules/SeriesTypes/Financial/CandleStickTab.xaml"), CodeFile("Modules/SeriesTypes/Financial/ValueSelectorItem.(cs)"), CodeFile("DataModels/FinancialDataLoader.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class FinancialSeriesDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Friend Class ReductionModeToReductionValueEnabledConverter
        Inherits ForwardOnlyValueConverter

        Public Overrides Function Convert(ByVal value As Object, ByVal targetType As Type, ByVal parameter As Object, ByVal culture As CultureInfo) As Object
            If value.GetType() IsNot GetType(ReductionColorMode) Then Return value
            Dim mode As ReductionColorMode = CType(value, ReductionColorMode)
            Select Case mode
                Case ReductionColorMode.OpenToCloseValue
                    Return False
                Case ReductionColorMode.PreviousToCurrentPoint
                    Return True
                Case Else
                    Return value
            End Select
        End Function
    End Class
End Namespace
