using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.TabControl.PinnedTabs {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.PinnedTabs/MainView.xaml",
        "Modules/TabControl.PinnedTabs/MainViewModel.(cs)")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
