using System;
using System.Globalization;
using DevExpress.Xpf.Charts;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/SeriesTypes/Financial/FinancialSeriesDemo.xaml"),
     CodeFile("Modules/SeriesTypes/Financial/StockTab.xaml"),
     CodeFile("Modules/SeriesTypes/Financial/CandleStickTab.xaml"),
     CodeFile("Modules/SeriesTypes/Financial/ValueSelectorItem.(cs)"),
     CodeFile("DataModels/FinancialDataLoader.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class FinancialSeriesDemo : ChartsDemoModule {
        public FinancialSeriesDemo() {
            InitializeComponent();
        }
    }

    class ReductionModeToReductionValueEnabledConverter : ForwardOnlyValueConverter {
        public override object Convert(object value, Type targetType, object parameter, CultureInfo culture) {
            if (value.GetType() != typeof(ReductionColorMode))
                return value;
            ReductionColorMode mode = (ReductionColorMode)value;
            switch (mode) {
                case ReductionColorMode.OpenToCloseValue:
                    return false;
                case ReductionColorMode.PreviousToCurrentPoint:
                    return true;
                default:
                    return value;
            };
        }
    }
}
