using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.TabControl.Views {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.Views/MainView.xaml",
        "Modules/TabControl.Views/MainViewModel.(cs)")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
