using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/SeriesTypes/Bars/BarsDemo.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/StackedBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/FullStackedBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideStackedBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideStackedBarTab.xaml.(cs)"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideFullStackedBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideFullStackedBarTab.xaml.(cs)"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideRangeBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/OverlappedRangeBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/SideBySideBar3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/ManhattanBarTab.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/CustomBarModel.xaml"),
     CodeFile("Modules/SeriesTypes/Bars/Bar2DKindToTickmarksLengthConverter.(cs)"),
     CodeFile("DataModels/AgeStructure.(cs)"),
     CodeFile("DataModels/DevAVSalesMixByRegion.(cs)"),
     CodeFile("DataModels/DevAVSalesByYear.(cs)"),
     CodeFile("DataModels/OilPrices.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class BarsDemo : ChartsDemoModule {
        public BarsDemo() {
            InitializeComponent();
        }
    }
}
