Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Windows
Imports System.Windows.Controls
Imports System.Windows.Markup
Imports DevExpress.Mvvm.UI
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/Interaction/DrillDown.xaml"), CodeFile("Modules/Interaction/DrillDown.xaml.(cs)"), CodeFile("Modules/Interaction/DrillDownViewModel.(cs)"), CodeFile("DataModels/DevAVSalesData.(cs)"), CodeFile("DataModels/DevAVHierarchicalSalesData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class DrillDownDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Friend Class ChildrenSelector
        Inherits MarkupExtension
        Implements IChildrenSelector

        Public Property BranchTemplate As DataTemplate

        Public Property CategoryTemplate As DataTemplate

        Public Property ProductTemplate As DataTemplate

        Private Function SelectChildren(ByVal item As Object) As IEnumerable Implements IChildrenSelector.SelectChildren
            If TypeOf item Is DevAVBranch Then Return New List(Of DevAVBranch) From {CType(item, DevAVBranch)}
            If TypeOf item Is DevAVProductCategory Then Return CType(item, DevAVProductCategory).Products
            If TypeOf item Is DevAVProduct Then
                Return New List(Of DevAVProduct) From {CType(item, DevAVProduct)}
            Else
                Return Nothing
            End If
        End Function

        Public Overrides Function ProvideValue(ByVal serviceProvider As IServiceProvider) As Object
            Return Me
        End Function
    End Class

    Friend Class DevAVSeriesTemplateSelector
        Inherits DataTemplateSelector

        Public Property BranchStackedBarTemplate As DataTemplate

        Public Property BranchColorEachBarTemplate As DataTemplate

        Public Property SingleProductTemplate As DataTemplate

        Public Property ProductTemplate As DataTemplate

        Public Overrides Function SelectTemplate(ByVal item As Object, ByVal container As DependencyObject) As DataTemplate
            Dim diagram As Diagram = CType(container, Diagram)
            If TypeOf item Is DevAVBranch AndAlso diagram.BreadcrumbItems.Count = 1 Then Return BranchStackedBarTemplate
            If TypeOf item Is DevAVBranch Then Return BranchColorEachBarTemplate
            If TypeOf item Is DevAVProduct AndAlso TypeOf diagram.BreadcrumbItems(diagram.BreadcrumbItems.Count - 1).SourceObject Is DevAVProduct Then Return SingleProductTemplate
            If TypeOf item Is DevAVProduct Then
                Return ProductTemplate
            Else
                Return Nothing
            End If
        End Function
    End Class

    Friend Class DrillDownStateChangedEventArgsConverter
        Inherits EventArgsConverterBase(Of DrillDownStateChangedEventArgs)

        Protected Overrides Function Convert(ByVal sender As Object, ByVal args As DrillDownStateChangedEventArgs) As Object
            Dim breadcrumbPath As List(Of Object) = New List(Of Object)(args.BreadcrumbItems.Count)
            For Each breadcrumbItem As BreadcrumbItem In args.BreadcrumbItems
                breadcrumbPath.Add(breadcrumbItem.SourceObject)
            Next

            Return breadcrumbPath
        End Function
    End Class
End Namespace
