Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/Panes/PanesDemo.xaml"), CodeFile("Modules/ChartElements/Panes/LinearPaneLayoutTab.xaml"), CodeFile("Modules/ChartElements/Panes/GridPaneLayoutTab.xaml"), CodeFile("DataModels/WebSitePerformanceIndicator.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class PanesDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
