using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/Interaction/RangeControlIntegration.xaml"),
     CodeFile("Modules/Interaction/RangeControlIntegration.xaml.(cs)"),
     CodeFile("DataModels/ExchangeRatesModel.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class RangeControlIntegrationDemo : ChartsDemoModule {
        public RangeControlIntegrationDemo() {
            InitializeComponent();
        }
    }
}
