using DevExpress.Xpf.DemoBase;

namespace DockingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ColorizedTabs.xaml",
        "ViewModels/ColorizedTabsViewModel.(cs)")]
    public partial class ColorizedTabs : DockingDemoModule {
        public ColorizedTabs() {
            InitializeComponent();
        }
    }
}
