using DevExpress.Xpf.DemoBase;

namespace DockingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/PinnedTabs.xaml",
        "ViewModels/PinnedTabsViewModel.(cs)")]
    public partial class PinnedTabs : DockingDemoModule {
        public PinnedTabs() {
            InitializeComponent();
        }
    }
}
