Imports DevExpress.Mvvm
Imports System.ComponentModel

' This class demonstrates the code that will be generated by the POCO mechanism at runtime
Namespace MVVMDemo.Commands

    Public Class POCOCommandsChangeNotificationsViewModel_RuntimeGeneratedCode
        Inherits POCOCommandsChangeNotificationsViewModel
        Implements INotifyPropertyChanged

        Private _SaveCommand As DelegateCommand

        Public ReadOnly Property SaveCommand As DelegateCommand
            Get
                Return If(_SaveCommand, Function()
                    _SaveCommand = New DelegateCommand(AddressOf Save, AddressOf CanSave, useCommandManager:=False)
                    Return _SaveCommand
                End Function())
            End Get
        End Property

#Region "properties"
        Public Overrides Property CanExecuteSaveCommand As Boolean
            Get
                Return MyBase.CanExecuteSaveCommand
            End Get

            Set(ByVal value As Boolean)
                If MyBase.CanExecuteSaveCommand = value Then Return
                MyBase.CanExecuteSaveCommand = value
                OnCanExecuteSaveCommandChanged()
                RaisePropertyChanged("CanExecuteSaveCommand")
            End Set
        End Property

#End Region
#Region "INotifyPropertyChanged implementation"
        Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

        Private Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim handler = PropertyChangedEvent
            If handler IsNot Nothing Then handler(Me, New PropertyChangedEventArgs(propertyName))
        End Sub
#End Region
    End Class
End Namespace
