Imports DevExpress.Xpf.DemoBase

Namespace DockingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/PinnedTabs.xaml", "ViewModels/PinnedTabsViewModel.(cs)")>
    Public Partial Class PinnedTabs
        Inherits DockingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
