Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Customization/AppointmentCustomizationDemoModule.xaml", "ViewModels/Customization/AppointmentCustomizationDemoViewModel.(cs)")>
    Public Partial Class AppointmentCustomizationDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
