Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Customization/TimeRulerDemoModule.xaml", "ViewModels/Customization/TimeRulerDemoViewModel.(cs)")>
    Public Partial Class TimeRulerDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
