Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Customization/TimeRegionsDemoModule.xaml", "ViewModels/Customization/TimeRegionsDemoViewModel.(cs)")>
    Public Partial Class TimeRegionsDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
