Imports DevExpress.Xpf.DemoBase
Imports DevExpress.Xpf.Scheduling
Imports SchedulingDemo.ViewModels

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Customization/WindowsCustomizationDemoModule.xaml", "Modules/Customization/WindowsCustomizationDemoModule.xaml.(cs)", "Modules/Customization/CustomWindows/CustomAppointmentWindow.xaml", "Modules/Customization/CustomWindows/CustomGotoDateWindow.xaml", "Modules/Customization/CustomWindows/CustomTimeRulerWindow.xaml", "ViewModels/Customization/WindowsCustomizationDemoViewModel.(cs)", "ViewModels/Customization/CustomWindows/CustomTimeRulerWindowViewModel.(cs)")>
    Public Partial Class WindowsCustomizationDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub OnTimeRulerWindowShowing(ByVal sender As Object, ByVal e As TimeRulerWindowShowingEventArgs)
            e.Window.DataContext = New CustomTimeRulerWindowViewModel(e.TimeRuler, scheduler.TimeZone)
        End Sub
    End Class
End Namespace
