Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataAnalysis/ErrorBars.xaml"), CodeFile("DataModels/ErrorBarsData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class ErrorBarsDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
