Imports System.Windows
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataAnalysis/FinancialIndicators.xaml"), CodeFile("Modules/DataAnalysis/FinancialIndicators.xaml.(cs)"), CodeFile("DataModels/FinancialDataGenerator.(cs)"), CodeFile("DataModels/FinancialDataPoint.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class FinancialIndicatorsDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
            chart.DataSource = FinancialDataGenerator.Generate()
        End Sub

        Private Sub chart_BoundDataChanged(ByVal sender As Object, ByVal e As RoutedEventArgs)
            fibonacciArcs.Argument1 = Date.Now.Date.AddDays(-165)
            fibonacciArcs.Argument2 = Date.Now.Date.AddDays(-140)
            fibonacciFans.Argument1 = Date.Now.Date.AddDays(-66)
            fibonacciFans.Argument2 = Date.Now.Date.AddDays(-49)
            Dim max As Date = Date.Now.Date.AddDays(2)
            Dim min As Date = max.AddDays(-185)
            xVisualRange.SetMinMaxValues(min, max)
        End Sub
    End Class
End Namespace
