Imports System
Imports System.Globalization
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataAnalysis/MovingAverageAndRegressionLine.xaml"), CodeFile("Modules/DataAnalysis/MovingAverageAndRegressionLine.xaml.(cs)"), CodeFile("DataModels/SimpleDataPoint.(cs)"), CodeFile("DataModels/PointGenerator.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class MovingAverageAndRegressionLineDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub chart_QueryChartCursor(ByVal sender As Object, ByVal e As QueryChartCursorEventArgs)
            e.CursorImageOffset = New Windows.Point(1000000, 1000000)
        End Sub
    End Class

    Friend Class MovingAverageKindToEnvelopePercentEnabledConverter
        Inherits ForwardOnlyValueConverter

        Public Overrides Function Convert(ByVal value As Object, ByVal targetType As Type, ByVal parameter As Object, ByVal culture As CultureInfo) As Object
            If value.GetType() IsNot GetType(MovingAverageKind) Then Return value
            If value.Equals(MovingAverageKind.MovingAverage) Then
                Return False
            Else
                Return True
            End If
        End Function
    End Class
End Namespace
