Imports DevExpress.Mvvm.DataAnnotations
Imports System.ComponentModel.DataAnnotations

Namespace GridDemo

    <MetadataType(GetType(DataAnnotationsElement2Metadata))>
    Public Class DataAnnotationsElement2_FluentAPI

        Public Property ID As Integer

        Public Property Employer As String

        Public Property FirstName As String

        Public Property LastName As String

        Public ReadOnly Property FullName As String
            Get
                Return FirstName & " " & LastName
            End Get
        End Property

        Public Property Age As Integer

        Public Property SSN As String

        Public Property Department As String
    End Class

    Public Module DataAnnotationsElement2Metadata

        Public Sub BuildMetadata(ByVal builder As MetadataBuilder(Of DataAnnotationsElement2_FluentAPI))
            builder.Property(Function(p) p.ID).NotAutoGenerated()
            builder.Property(Function(p) p.Employer).NotEditable()
            builder.Property(Function(p) p.FirstName).DisplayName("First name").Required()
            builder.Property(Function(p) p.LastName).DisplayName("Last name").Required()
            builder.Property(Function(p) p.FullName).DisplayName("Full name")
            builder.Property(Function(p) p.Age).DisplayFormatString("d2", applyDisplayFormatInEditMode:=True)
            builder.Property(Function(p) p.SSN).ReadOnly()
            builder.Property(Function(p) p.Department).NullDisplayText("Department not set")
        End Sub
    End Module
End Namespace
