using System;
using System.Collections.Generic;
using System.Windows;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Mvvm.UI.Interactivity;

namespace LayoutControlDemo {
    public class LayoutControlCustomizationBehavior : Behavior<DataLayoutControl> {
        public FrameworkElement SelectedItem {
            get { return (FrameworkElement)GetValue(SelectedItemProperty); }
            set { SetValue(SelectedItemProperty, value); }
        }
        public static readonly DependencyProperty SelectedItemProperty =
            DependencyProperty.Register("SelectedItem", typeof(FrameworkElement), typeof(LayoutControlCustomizationBehavior), new PropertyMetadata(null));

        public bool AllowCustomization {
            get { return (bool)GetValue(AllowCustomizationProperty); }
            set { SetValue(AllowCustomizationProperty, value); }
        }
        public static readonly DependencyProperty AllowCustomizationProperty =
            DependencyProperty.Register("AllowCustomization", typeof(bool), typeof(LayoutControlCustomizationBehavior), new PropertyMetadata(true, new PropertyChangedCallback(AllowCustomizationChanged)));

        static void AllowCustomizationChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) {
            ((LayoutControlCustomizationBehavior)d).OnAllowCustomizationChanged();
        }

        void OnAllowCustomizationChanged() {
            if(AssociatedObject != null && AssociatedObject.IsCustomization && !AllowCustomization)
                AssociatedObject.Controller.CustomizationController.SelectedElements.Clear();
        }

        protected override void OnAttached() {
            base.OnAttached();
            AssociatedObject.IsCustomizationChanged += OnIsCustomizationChanged;
            AssociatedObject.AutoGeneratedUI += OnAutoGeneratedUI;
        }

        protected override void OnDetaching() {
            AssociatedObject.AutoGeneratedUI -= OnAutoGeneratedUI;
            AssociatedObject.IsCustomizationChanged -= OnIsCustomizationChanged;
            base.OnDetaching();
        }

        void OnAutoGeneratedUI(object sender, EventArgs e) {
            if(AssociatedObject.AutoGeneratedItemsLocation == DataLayoutControlAutoGeneratedItemsLocation.AvailableItems)
                AssociatedObject.IsCustomization = true;
        }

        void OnIsCustomizationChanged(object sender, EventArgs e) {
            if(AssociatedObject.IsCustomization)
                AssociatedObject.Controller.CustomizationController.SelectionChanged += layoutItems_SelectionChanged;
            else
                AssociatedObject.Controller.CustomizationController.SelectionChanged -= layoutItems_SelectionChanged;
            SelectedItem = null;
        }
        void layoutItems_SelectionChanged(object sender, LayoutControlSelectionChangedEventArgs e) {
            if(e.SelectedElements.Count == 1 && e.SelectedElements[0] is DataLayoutItem)
                SelectedItem = e.SelectedElements[0];
            else
                SelectedItem = null;
        }

    }
}
