Imports System
Imports System.Globalization
Imports System.Collections.Generic
Imports System.Xml.Linq
Imports DevExpress.Xpf.DemoBase

Namespace TreeMapDemo

    <CodeFile("Modules/TreeMap/Hierarchical.xaml")>
    <CodeFile("Modules/TreeMap/Hierarchical.xaml.(cs)")>
    <NoAutogeneratedCodeFiles>
    Public Partial Class Hierarchical
        Inherits TreeMapDemoModule

        Public Sub New()
            InitializeComponent()
            DataContext = LoadDataFromXML()
        End Sub

        Private Function LoadDataFromXML() As List(Of CountryEnergyInfo)
            Dim document As XDocument = LoadXDocumentFromResources("/Data/EnergyStatistic.xml")
            Dim infos As List(Of CountryEnergyInfo) = New List(Of CountryEnergyInfo)()
            If document IsNot Nothing Then
                For Each element As XElement In document.Element("ArrayOfEnergyStatistic").Elements()
                    Dim energyInfo As CountryEnergyInfo = New CountryEnergyInfo()
                    energyInfo.Country = element.Attribute("Country").Value
                    For Each energyElement As XElement In element.Elements()
                        Dim item As EnergyStatisticItem = New EnergyStatisticItem()
                        item.TypeName = energyElement.Attribute("TypeName").Value
                        item.Value = Convert.ToDouble(energyElement.Attribute("Value").Value, CultureInfo.InvariantCulture)
                        energyInfo.EnergyStatistic.Add(item)
                    Next

                    infos.Add(energyInfo)
                Next
            End If

            Return infos
        End Function
    End Class

    Public Class CountryEnergyInfo

        Private ReadOnly energyStatisticField As List(Of EnergyStatisticItem) = New List(Of EnergyStatisticItem)()

        Public ReadOnly Property EnergyStatistic As List(Of EnergyStatisticItem)
            Get
                Return energyStatisticField
            End Get
        End Property

        Public Property Country As String
    End Class

    Public Class EnergyStatisticItem

        Public Property Value As Double

        Public Property TypeName As String
    End Class
End Namespace
