Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/XyzChart/DataBinding/DataBindingDemo.xaml")>
    <CodeFile("DataPoint3DBindingViewModel.cs")>
    <CodeFile("Modules/XyzChart/DataBinding/DataPoint3DBindingTab.xaml")>
    <CodeFile("Modules/XyzChart/DataBinding/RegularGridDataTab.xaml")>
    <CodeFile("DataModels/HightMapGenerator.(cs)")>
    <NoAutogeneratedCodeFiles>
    Public Partial Class DataBindingDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
