using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/AxisAndSeriesLabels.xaml"),
     CodeFile("DataModels/MarsTemperatureData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class AxisAndSeriesLabelsDemo : ChartsDemoModule {
        public AxisAndSeriesLabelsDemo() {
            InitializeComponent();
        }
    }
}
