using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/ConstantLinesAndStrips.xaml"),
     CodeFile("DataModels/OperatingSurfaceTemperatureData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class ConstantLinesAndStripsDemo : ChartsDemoModule {
        public ConstantLinesAndStripsDemo() {
            InitializeComponent();
        }
    }
}
