using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/LogarithmicScale.xaml"),
     CodeFile("DataModels/HeadphoneComparisonDataReader.(cs)"),
     CodeFile("Modules/ChartElements/LogarithmicScaleViewModel.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class LogarithmicScaleDemo : ChartsDemoModule {
        public LogarithmicScaleDemo() {
            InitializeComponent();
        }
    }
}
