using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/ScaleBreaks.xaml"),
     CodeFile("DataModels/PlanetData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class ScaleBreaksDemo : ChartsDemoModule {
        public ScaleBreaksDemo() {
            InitializeComponent();
        }
    }
}
