using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/SeriesTypes/PointsAndBubbles/PointsAndBubblesDemo.xaml"),
     CodeFile("Modules/SeriesTypes/PointsAndBubbles/PointTab.xaml"),
     CodeFile("Modules/SeriesTypes/PointsAndBubbles/BubbleTab.xaml"),
     CodeFile("Modules/SeriesTypes/PointsAndBubbles/Point3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/PointsAndBubbles/Bubble3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/CustomMarkerModel.xaml"),
     CodeFile("DataModels/HighestGrossingFilmsByYear.(cs)"),
     CodeFile("DataModels/DevAVSalesByYear.(cs)"),
     CodeFile("DataModels/PopulationGenerator.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class PointsAndBubblesDemo : ChartsDemoModule {
        public PointsAndBubblesDemo() {
            InitializeComponent();
        }
    }
}
