Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/Highlighted/RealTimeChart.xaml"), CodeFile("Modules/Highlighted/RealTimeChart.xaml.(cs)"), CodeFile("DataModels/SensorDataGenerator.(cs)"), CodeFile("Modules/Highlighted/RealTimeChartViewModel.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class RealTimeChartDemo
        Inherits ChartsDemoModule

        Private ReadOnly Property ViewModel As RealTimeChartViewModel
            Get
                Return TryCast(DataContext, RealTimeChartViewModel)
            End Get
        End Property

        Public Overrides ReadOnly Property ModuleChartControl As ChartControl
            Get
                Return chart
            End Get
        End Property

        Public Sub New()
            InitializeComponent()
            AddHandler Loaded, Sub(s, e) SetVisualRange()
            AddHandler Unloaded, Sub(s, e) ViewModel.Unload()
        End Sub

        Public Overrides Sub OnStopModule()
            ViewModel.PauseTimer()
        End Sub

        Public Overrides Sub OnStartModule()
            ViewModel.ResumeTimer()
        End Sub

        Public Sub SetVisualRange()
            Dim axisX As AxisX2D = CType(chart.Diagram, XYDiagram2D).ActualAxisX
            Dim wholeRangeMax As Date = CDate(axisX.ActualWholeRange.ActualMaxValue)
            axisX.ActualVisualRange.SetMinMaxValues(wholeRangeMax.AddSeconds(-14), wholeRangeMax)
        End Sub
    End Class
End Namespace
