Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/Highlighted/RealTime3DChartDemo.xaml"), CodeFile("Modules/Highlighted/RealTime3DChartDemoViewModel.(cs)"), CodeFile("DataModels/RealTime3DDataGenerator.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class RealTime3DChartDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
