Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/Highlighted/TornadoChart.xaml"), CodeFile("Modules/Highlighted/TornadoChart.xaml.(cs)"), CodeFile("Modules/Highlighted/TornadoChartViewModel.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class TornadoChartDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
