using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.TabControl.ColorizedTabs {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.ColorizedTabs/MainView.xaml",
        "Modules/TabControl.ColorizedTabs/MainViewModel.(cs)")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
