Imports System.Linq
Imports System.Windows
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/Annotations.xaml"), CodeFile("Modules/ChartElements/Annotations.xaml.(cs)"), CodeFile("DataModels/MarsTemperatureData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class AnnotationsDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub BoundDataChanged(ByVal sender As Object, ByVal e As RoutedEventArgs)
            Dim min = splineSeries.Points.Aggregate(Function(seed, current) If(seed.Value < current.Value, seed, current))
            minimumPoint.SeriesPoint = min
            minimumAnnotationContent.Text = "Minimum: " & min.Value
            Dim max = splineSeries.Points.Aggregate(Function(seed, current) If(seed.Value > current.Value, seed, current))
            maximumPoint.SeriesPoint = max
            maximumAnnotationContent.Text = "Maximum: " & max.Value
        End Sub
    End Class
End Namespace
