Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/AxisAndSeriesLabels.xaml"), CodeFile("DataModels/MarsTemperatureData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class AxisAndSeriesLabelsDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
