Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/ConstantLinesAndStrips.xaml"), CodeFile("DataModels/OperatingSurfaceTemperatureData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class ConstantLinesAndStripsDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
