Imports System.Windows
Imports System.Windows.Data
Imports System.Windows.Media
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/Legends.xaml"), CodeFile("Modules/ChartElements/Legends.xaml.(cs)"), CodeFile("DataModels/ResourceUsageData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class LegendsDemo
        Inherits ChartsDemoModule

        Public Shared ReadOnly ChartPaletteProperty As DependencyProperty = DependencyProperty.Register("ChartPalette", GetType(Palette), GetType(LegendsDemo), New PropertyMetadata(AddressOf OnChartPaletteChanged))

        Private Shared Sub OnChartPaletteChanged(ByVal d As DependencyObject, ByVal e As DependencyPropertyChangedEventArgs)
            Dim demo As LegendsDemo = TryCast(d, LegendsDemo)
            If demo IsNot Nothing Then demo.ColorizeSeries()
        End Sub

        Public Sub New()
            InitializeComponent()
            Dim myBinding As Binding = New Binding("Palette")
            myBinding.Source = chart
            myBinding.Mode = BindingMode.OneWay
            SetBinding(ChartPaletteProperty, myBinding)
        End Sub

        Private Sub ColorizeSeries()
            Dim brush As SolidColorBrush = New SolidColorBrush(chart.Palette(0))
            brush.Freeze()
            CType(chart.Diagram.Series(3), XYSeries).Brush = brush
            brush = New SolidColorBrush(chart.Palette(1))
            brush.Freeze()
            CType(chart.Diagram.Series(4), XYSeries).Brush = brush
            brush = New SolidColorBrush(chart.Palette(2))
            brush.Freeze()
            CType(chart.Diagram.Series(5), XYSeries).Brush = brush
        End Sub
    End Class

    Friend Enum LegendMode
        Common
        SeparateInsidePane
        SeparateOutsidePane
    End Enum
End Namespace
