Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/LogarithmicScale.xaml"), CodeFile("DataModels/HeadphoneComparisonDataReader.(cs)"), CodeFile("Modules/ChartElements/LogarithmicScaleViewModel.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class LogarithmicScaleDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
