Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/ScaleBreaks.xaml"), CodeFile("DataModels/PlanetData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class ScaleBreaksDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
