using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Scheduling.VisualData;
using System;
using System.Windows;
using System.Windows.Controls;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Highlighted/EmployeeWorkScheduleDemoModule.xaml",
        "ViewModels/Highlighted/EmployeeWorkScheduleDemoViewModel.(cs)",
        "Themes/EmployeeWorkSchedule.xaml")]
    public partial class EmployeeWorkScheduleDemoModule : SchedulingDemoModule {
        public EmployeeWorkScheduleDemoModule() {
            InitializeComponent();
        }
    }

    public class TimeRegionTemplateSelector : DataTemplateSelector {
        public DataTemplate DinnerTemplate { get; set; }
        public object DinnerId { get; set; }

        public override DataTemplate SelectTemplate(object item, DependencyObject container) {
            var vm = (TimeRegionViewModel)item;
            return vm.TimeRegion.Id == DinnerId ? DinnerTemplate : null;
        }
    }
}
