using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Scheduling;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Highlighted/FilteringDemoModule.xaml",
        "Modules/Highlighted/FilteringDemoModule.xaml.(cs)",
        "ViewModels/Highlighted/FilteringDemoViewModel.(cs)")]
    public partial class FilteringDemoModule : SchedulingDemoModule {
        public FilteringDemoModule() {
            InitializeComponent();
            Loaded += OnFilteringDemoModuleLoaded;
        }
        void OnFilteringDemoModuleLoaded(object sender, System.Windows.RoutedEventArgs e) {
            resourceTreeControl.TreeView.AutoWidth = false;
        }
        void OnAppointmentWindowShowing(object sender, AppointmentWindowShowingEventArgs e) {
            e.Window.DataContext = MedicalAppointmentWindowViewModel.Create(e.Appointment, scheduler);
        }
    }
}
