using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/XyzChart/DataBinding/DataBindingDemo.xaml")]
    [CodeFile("DataPoint3DBindingViewModel.cs")]
    [CodeFile("Modules/XyzChart/DataBinding/DataPoint3DBindingTab.xaml")]
    [CodeFile("Modules/XyzChart/DataBinding/RegularGridDataTab.xaml")]
    [CodeFile("DataModels/HightMapGenerator.(cs)")]
    [NoAutogeneratedCodeFiles]
    public partial class DataBindingDemo : ChartsDemoModule {
        public DataBindingDemo() {
            InitializeComponent();
        }
    }
}
