using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.TabControl.CustomTheme {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.CustomTheme/MainView.xaml",
        "Modules/TabControl.CustomTheme/MainViewModel.(cs)")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
