using DevExpress.Mvvm;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Mvvm.Gantt;
using DevExpress.Xpf.Gantt;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GanttDemo {
    public class PrintingViewModel : PrintingViewModelBase {
        public List<GanttTask> Items { get; private set; }
        public List<GanttResource> Resources { get; private set; }
        public List<GanttResourceLink> ResourceLinks { get; private set; }

        public PrintingViewModel() {
            Items = CreateData();
            Resources = CreateResources();
            ResourceLinks = CreateResourceLinks();
        }

        List<GanttTask> CreateData() {
            var tasks = new List<GanttTask>();
            #region Data generation
            tasks.Add(new GanttTask { Id = 0, Name = "Commercial Construction", StartDate = new DateTime(2020, 8, 11, 8, 0, 0), FinishDate = new DateTime(2021, 12, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 2, ParentId = 0, Name = "General Conditions", StartDate = new DateTime(2020, 8, 11, 8, 0, 0), FinishDate = new DateTime(2020, 9, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 3, ParentId = 2, Name = "Receive notice to proceed and sign contract", StartDate = new DateTime(2020, 8, 11, 8, 0, 0), FinishDate = new DateTime(2020, 8, 13, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 4, ParentId = 2, Name = "Submit bond and insurance documents", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 17, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 5, ParentId = 2, Name = "Prepare and submit project schedule", StartDate = new DateTime(2020, 8, 18, 8, 0, 0), FinishDate = new DateTime(2020, 8, 19, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 6, ParentId = 2, Name = "Prepare and submit schedule of values", StartDate = new DateTime(2020, 8, 20, 8, 0, 0), FinishDate = new DateTime(2020, 8, 21, 17, 0, 0), Progress = 0.5 });
            tasks.Add(new GanttTask { Id = 7, ParentId = 2, Name = "Obtain building permits", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 19, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 8, ParentId = 2, Name = "Submit preliminary shop drawings", StartDate = new DateTime(2020, 8, 20, 8, 0, 0), FinishDate = new DateTime(2020, 9, 2, 17, 0, 0), Progress = 0.3 });
            tasks.Add(new GanttTask { Id = 9, ParentId = 2, Name = "Submit monthly requests for payment", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 14, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 10, ParentId = 0, Name = "Long Lead Procurement", StartDate = new DateTime(2020, 8, 17, 8, 0, 0), FinishDate = new DateTime(2020, 11, 20, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 11, ParentId = 10, Name = "Submit shop drawings and order long lead items - steel", StartDate = new DateTime(2020, 8, 17, 8, 0, 0), FinishDate = new DateTime(2020, 8, 28, 17, 0, 0), Progress = 0.4 });
            tasks.Add(new GanttTask { Id = 12, ParentId = 10, Name = "Submit shop drawings and order long lead items - roofing", StartDate = new DateTime(2020, 9, 3, 8, 0, 0), FinishDate = new DateTime(2020, 9, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 13, ParentId = 10, Name = "Submit shop drawings and order long lead items - elevator", StartDate = new DateTime(2020, 9, 3, 8, 0, 0), FinishDate = new DateTime(2020, 9, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 14, ParentId = 10, Name = "Submit shop drawings and order long lead items - plumbing", StartDate = new DateTime(2020, 9, 3, 8, 0, 0), FinishDate = new DateTime(2020, 9, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 15, ParentId = 10, Name = "Submit shop drawings and order long lead items - electric", StartDate = new DateTime(2020, 9, 3, 8, 0, 0), FinishDate = new DateTime(2020, 9, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 16, ParentId = 10, Name = "Submit shop drawings and order long lead items - HVAC", StartDate = new DateTime(2020, 9, 3, 8, 0, 0), FinishDate = new DateTime(2020, 9, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 17, ParentId = 10, Name = "Detail, fabricate and deliver steel", StartDate = new DateTime(2020, 8, 31, 8, 0, 0), FinishDate = new DateTime(2020, 11, 20, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 18, ParentId = 0, Name = "Mobilize on Site", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 27, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 19, ParentId = 18, Name = "Install temporary power", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 17, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 20, ParentId = 18, Name = "Install temporary water service", StartDate = new DateTime(2020, 8, 14, 8, 0, 0), FinishDate = new DateTime(2020, 8, 17, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 21, ParentId = 18, Name = "Set up site office", StartDate = new DateTime(2020, 8, 18, 8, 0, 0), FinishDate = new DateTime(2020, 8, 20, 17, 0, 0), Progress = 1 });
            tasks.Add(new GanttTask { Id = 22, ParentId = 18, Name = "Set line and grade benchmarks", StartDate = new DateTime(2020, 8, 21, 8, 0, 0), FinishDate = new DateTime(2020, 8, 25, 17, 0, 0), Progress = 0.2 });
            tasks.Add(new GanttTask { Id = 23, ParentId = 18, Name = "Prepare site - lay down yard and temporary fencing", StartDate = new DateTime(2020, 8, 26, 8, 0, 0), FinishDate = new DateTime(2020, 8, 27, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 24, ParentId = 0, Name = "Site Grading and Utilities", StartDate = new DateTime(2020, 8, 28, 8, 0, 0), FinishDate = new DateTime(2020, 10, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 25, ParentId = 24, Name = "Clear and grub site", StartDate = new DateTime(2020, 8, 28, 8, 0, 0), FinishDate = new DateTime(2020, 9, 1, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 26, ParentId = 24, Name = "Stone site access and temporary parking area", StartDate = new DateTime(2020, 9, 2, 8, 0, 0), FinishDate = new DateTime(2020, 9, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 27, ParentId = 24, Name = "Rough grade site (cut and fill)", StartDate = new DateTime(2020, 9, 4, 8, 0, 0), FinishDate = new DateTime(2020, 9, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 28, ParentId = 24, Name = "Install storm drainage", StartDate = new DateTime(2020, 9, 11, 8, 0, 0), FinishDate = new DateTime(2020, 9, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 29, ParentId = 24, Name = "Install exterior fire line and building fire riser", StartDate = new DateTime(2020, 9, 11, 8, 0, 0), FinishDate = new DateTime(2020, 9, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 30, ParentId = 24, Name = "Perform final site grading", StartDate = new DateTime(2020, 9, 25, 8, 0, 0), FinishDate = new DateTime(2020, 10, 8, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 31, ParentId = 24, Name = "Erect building batter boards and layout building", StartDate = new DateTime(2020, 10, 9, 8, 0, 0), FinishDate = new DateTime(2020, 10, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 32, ParentId = 0, Name = "Foundations", StartDate = new DateTime(2020, 10, 16, 8, 0, 0), FinishDate = new DateTime(2020, 12, 1, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 33, ParentId = 32, Name = "Excavate foundations", StartDate = new DateTime(2020, 10, 16, 8, 0, 0), FinishDate = new DateTime(2020, 10, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 34, ParentId = 32, Name = "Excavate elevator pit", StartDate = new DateTime(2020, 10, 16, 8, 0, 0), FinishDate = new DateTime(2020, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 35, ParentId = 32, Name = "Form column piers and spread foundations", StartDate = new DateTime(2020, 10, 30, 8, 0, 0), FinishDate = new DateTime(2020, 11, 4, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 36, ParentId = 32, Name = "Rough-in electric and plumbing in elevator", StartDate = new DateTime(2020, 10, 20, 8, 0, 0), FinishDate = new DateTime(2020, 10, 23, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 37, ParentId = 32, Name = "Form elevator pit walls", StartDate = new DateTime(2020, 10, 26, 8, 0, 0), FinishDate = new DateTime(2020, 10, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 38, ParentId = 32, Name = "Set reinforcing and anchor bolts", StartDate = new DateTime(2020, 11, 5, 8, 0, 0), FinishDate = new DateTime(2020, 11, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 39, ParentId = 32, Name = "Pour column piers and foundations", StartDate = new DateTime(2020, 11, 11, 8, 0, 0), FinishDate = new DateTime(2020, 11, 17, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 40, ParentId = 32, Name = "Pour concrete elevator walls", StartDate = new DateTime(2020, 10, 30, 8, 0, 0), FinishDate = new DateTime(2020, 10, 30, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 41, ParentId = 32, Name = "Cure elevator wall concrete", StartDate = new DateTime(2020, 11, 2, 8, 0, 0), FinishDate = new DateTime(2020, 11, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 42, ParentId = 32, Name = "Cure piers and foundations", StartDate = new DateTime(2020, 11, 18, 8, 0, 0), FinishDate = new DateTime(2020, 11, 26, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 43, ParentId = 32, Name = "Strip wall forms", StartDate = new DateTime(2020, 11, 11, 8, 0, 0), FinishDate = new DateTime(2020, 11, 11, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 44, ParentId = 32, Name = "Strip column piers and foundation forms", StartDate = new DateTime(2020, 11, 27, 8, 0, 0), FinishDate = new DateTime(2020, 12, 1, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 45, ParentId = 32, Name = "Install pneumatic tube in elevator pit", StartDate = new DateTime(2020, 11, 12, 8, 0, 0), FinishDate = new DateTime(2020, 11, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 46, ParentId = 32, Name = "Prepare and pour concrete floor in elevator pit", StartDate = new DateTime(2020, 11, 17, 8, 0, 0), FinishDate = new DateTime(2020, 11, 17, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 47, ParentId = 0, Name = "Steel Erection", StartDate = new DateTime(2020, 12, 2, 8, 0, 0), FinishDate = new DateTime(2021, 2, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 48, ParentId = 47, Name = "Erect steel columns, beams and joist - 1st and 2nd floors", StartDate = new DateTime(2020, 12, 2, 8, 0, 0), FinishDate = new DateTime(2020, 12, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 49, ParentId = 47, Name = "Erect steel columns, beams and joist - 3rd floor and roof", StartDate = new DateTime(2020, 12, 16, 8, 0, 0), FinishDate = new DateTime(2020, 12, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 50, ParentId = 47, Name = "Install miscellaneous iron and bracing - 1st and 2nd floors", StartDate = new DateTime(2020, 12, 16, 8, 0, 0), FinishDate = new DateTime(2020, 12, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 51, ParentId = 47, Name = "Install miscellaneous iron and bracing - 3rd floor and roof", StartDate = new DateTime(2020, 12, 30, 8, 0, 0), FinishDate = new DateTime(2021, 1, 12, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 52, ParentId = 47, Name = "Install stairs and miscellaneous iron railing", StartDate = new DateTime(2021, 1, 13, 8, 0, 0), FinishDate = new DateTime(2021, 1, 26, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 53, ParentId = 47, Name = "Touch-up paint on steel", StartDate = new DateTime(2021, 1, 27, 8, 0, 0), FinishDate = new DateTime(2021, 2, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 54, ParentId = 0, Name = "Form and Pour Concrete - Floors and Roof", StartDate = new DateTime(2020, 12, 16, 8, 0, 0), FinishDate = new DateTime(2021, 4, 13, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 55, ParentId = 54, Name = "Form 2nd floor including all floor openings", StartDate = new DateTime(2021, 2, 3, 8, 0, 0), FinishDate = new DateTime(2021, 2, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 56, ParentId = 54, Name = "Install rebar and in-floor utilities (including mechanical, electrical, plumbing)", StartDate = new DateTime(2020, 12, 16, 8, 0, 0), FinishDate = new DateTime(2020, 12, 22, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 57, ParentId = 54, Name = "Pour 2nd floor slab", StartDate = new DateTime(2021, 2, 10, 8, 0, 0), FinishDate = new DateTime(2021, 2, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 58, ParentId = 54, Name = "Cure 2nd floor slab", StartDate = new DateTime(2021, 2, 16, 8, 0, 0), FinishDate = new DateTime(2021, 2, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 59, ParentId = 54, Name = "Strip forms from 2nd floor slab", StartDate = new DateTime(2021, 2, 25, 8, 0, 0), FinishDate = new DateTime(2021, 2, 26, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 60, ParentId = 54, Name = "Form 3rd floor including all floor openings", StartDate = new DateTime(2021, 2, 25, 8, 0, 0), FinishDate = new DateTime(2021, 3, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 61, ParentId = 54, Name = "Install rebar and in-floor utilities (including mechanical, electrical, plumbing)", StartDate = new DateTime(2021, 2, 25, 8, 0, 0), FinishDate = new DateTime(2021, 3, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 62, ParentId = 54, Name = "Pour 3rd floor slab", StartDate = new DateTime(2021, 3, 4, 8, 0, 0), FinishDate = new DateTime(2021, 3, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 63, ParentId = 54, Name = "Cure 3rd floor slab", StartDate = new DateTime(2021, 3, 10, 8, 0, 0), FinishDate = new DateTime(2021, 3, 18, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 64, ParentId = 54, Name = "Strip forms from 3rd floor slab", StartDate = new DateTime(2021, 3, 19, 8, 0, 0), FinishDate = new DateTime(2021, 3, 22, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 65, ParentId = 54, Name = "Form roof slab including all floor openings", StartDate = new DateTime(2021, 3, 19, 8, 0, 0), FinishDate = new DateTime(2021, 3, 25, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 66, ParentId = 54, Name = "Install rebar and in-floor utilities (including mechanical, electrical, plumbing)", StartDate = new DateTime(2021, 3, 19, 8, 0, 0), FinishDate = new DateTime(2021, 3, 25, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 67, ParentId = 54, Name = "Pour roof slab", StartDate = new DateTime(2021, 3, 26, 8, 0, 0), FinishDate = new DateTime(2021, 3, 31, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 68, ParentId = 54, Name = "Cure roof slab", StartDate = new DateTime(2021, 4, 1, 8, 0, 0), FinishDate = new DateTime(2021, 4, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 69, ParentId = 54, Name = "Strip forms from roof slab", StartDate = new DateTime(2021, 4, 12, 8, 0, 0), FinishDate = new DateTime(2021, 4, 13, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 70, ParentId = 54, Name = "Form 1st floor", StartDate = new DateTime(2021, 3, 1, 8, 0, 0), FinishDate = new DateTime(2021, 3, 4, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 71, ParentId = 54, Name = "Install electrical underground", StartDate = new DateTime(2021, 3, 1, 8, 0, 0), FinishDate = new DateTime(2021, 3, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 72, ParentId = 54, Name = "Install plumbing underground", StartDate = new DateTime(2021, 3, 1, 8, 0, 0), FinishDate = new DateTime(2021, 3, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 73, ParentId = 54, Name = "Install rebar and in-floor utilities", StartDate = new DateTime(2021, 3, 1, 8, 0, 0), FinishDate = new DateTime(2021, 3, 4, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 74, ParentId = 54, Name = "Pour 1st floor slab", StartDate = new DateTime(2021, 3, 8, 8, 0, 0), FinishDate = new DateTime(2021, 3, 11, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 75, ParentId = 54, Name = "Cure 1st floor slab", StartDate = new DateTime(2021, 3, 12, 8, 0, 0), FinishDate = new DateTime(2021, 3, 22, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 76, ParentId = 54, Name = "Strip forms from 1st floor slab", StartDate = new DateTime(2021, 3, 23, 8, 0, 0), FinishDate = new DateTime(2021, 3, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 77, ParentId = 0, Name = "Carpentry Work", StartDate = new DateTime(2021, 4, 14, 8, 0, 0), FinishDate = new DateTime(2021, 5, 4, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 78, ParentId = 77, Name = "Install exterior sheathing and metal studs", StartDate = new DateTime(2021, 4, 14, 8, 0, 0), FinishDate = new DateTime(2021, 5, 4, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 79, ParentId = 0, Name = "Masonry Work", StartDate = new DateTime(2021, 1, 13, 8, 0, 0), FinishDate = new DateTime(2021, 6, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 80, ParentId = 79, Name = "Rough-in plumbing at toilets and masonry walls", StartDate = new DateTime(2021, 3, 25, 8, 0, 0), FinishDate = new DateTime(2021, 4, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 81, ParentId = 79, Name = "Lay masonry at core, mechanical, and toilets", StartDate = new DateTime(2021, 1, 13, 8, 0, 0), FinishDate = new DateTime(2021, 2, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 82, ParentId = 79, Name = "Install exterior masonry work", StartDate = new DateTime(2021, 5, 5, 8, 0, 0), FinishDate = new DateTime(2021, 6, 8, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 83, ParentId = 79, Name = "Install roof drains", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 6, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 84, ParentId = 79, Name = "Install tile in toilet rooms", StartDate = new DateTime(2021, 4, 22, 8, 0, 0), FinishDate = new DateTime(2021, 5, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 85, ParentId = 79, Name = "Clean masonry", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 6, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 86, ParentId = 79, Name = "Clean toilet room tile", StartDate = new DateTime(2021, 5, 6, 8, 0, 0), FinishDate = new DateTime(2021, 5, 12, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 87, ParentId = 0, Name = "Roofing", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 7, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 88, ParentId = 87, Name = "Install flashing at parapet walls", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 6, 14, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 89, ParentId = 87, Name = "Pour lightweight concrete roof fill", StartDate = new DateTime(2021, 6, 15, 8, 0, 0), FinishDate = new DateTime(2021, 6, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 90, ParentId = 87, Name = "Install seamless roofing material", StartDate = new DateTime(2021, 6, 24, 8, 0, 0), FinishDate = new DateTime(2021, 6, 30, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 91, ParentId = 87, Name = "Spread stone ballast on seamless roof", StartDate = new DateTime(2021, 7, 1, 8, 0, 0), FinishDate = new DateTime(2021, 7, 7, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 92, ParentId = 87, Name = "Set rooftop equipment", StartDate = new DateTime(2021, 7, 8, 8, 0, 0), FinishDate = new DateTime(2021, 7, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 93, ParentId = 0, Name = "Window wall and store front closures", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 8, 31, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 94, ParentId = 93, Name = "Install window wall aluminum and glass", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 7, 13, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 95, ParentId = 93, Name = "Install interior stud walls and drywall", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 8, 17, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 96, ParentId = 93, Name = "Install interior doors and hardware", StartDate = new DateTime(2021, 8, 18, 8, 0, 0), FinishDate = new DateTime(2021, 8, 31, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 97, ParentId = 93, Name = "Install store front doors and hardware", StartDate = new DateTime(2021, 6, 9, 8, 0, 0), FinishDate = new DateTime(2021, 6, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 98, ParentId = 0, Name = "Building Finishes", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 11, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 99, ParentId = 98, Name = "Install millwork and wood trim", StartDate = new DateTime(2021, 8, 18, 8, 0, 0), FinishDate = new DateTime(2021, 9, 7, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 100, ParentId = 98, Name = "Paint walls and woodwork", StartDate = new DateTime(2021, 9, 8, 8, 0, 0), FinishDate = new DateTime(2021, 10, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 101, ParentId = 98, Name = "Install conduit at ceiling plenum space", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 8, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 102, ParentId = 98, Name = "Install duct in ceiling plenum space", StartDate = new DateTime(2021, 8, 18, 8, 0, 0), FinishDate = new DateTime(2021, 9, 7, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 103, ParentId = 98, Name = "Install ceiling grid", StartDate = new DateTime(2021, 9, 8, 8, 0, 0), FinishDate = new DateTime(2021, 9, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 104, ParentId = 98, Name = "Install ceiling tile", StartDate = new DateTime(2021, 9, 22, 8, 0, 0), FinishDate = new DateTime(2021, 10, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 105, ParentId = 98, Name = "Hang wallpaper", StartDate = new DateTime(2021, 9, 22, 8, 0, 0), FinishDate = new DateTime(2021, 10, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 106, ParentId = 98, Name = "Install building carpet", StartDate = new DateTime(2021, 10, 6, 8, 0, 0), FinishDate = new DateTime(2021, 11, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 107, ParentId = 98, Name = "Install hardware and accessories", StartDate = new DateTime(2021, 10, 6, 8, 0, 0), FinishDate = new DateTime(2021, 10, 26, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 108, ParentId = 98, Name = "Complete interior and exterior sod and plantings", StartDate = new DateTime(2021, 10, 6, 8, 0, 0), FinishDate = new DateTime(2021, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 109, ParentId = 98, Name = "Pave, curb, and stripe parking lot", StartDate = new DateTime(2021, 10, 20, 8, 0, 0), FinishDate = new DateTime(2021, 11, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 110, ParentId = 0, Name = "Elevators", StartDate = new DateTime(2021, 2, 10, 8, 0, 0), FinishDate = new DateTime(2021, 4, 6, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 111, ParentId = 110, Name = "Set elevator equipment in shafts", StartDate = new DateTime(2021, 2, 10, 8, 0, 0), FinishDate = new DateTime(2021, 3, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 112, ParentId = 110, Name = "Set equipment in mechanical room", StartDate = new DateTime(2021, 3, 10, 8, 0, 0), FinishDate = new DateTime(2021, 3, 23, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 113, ParentId = 110, Name = "Test and align doors and equipment", StartDate = new DateTime(2021, 3, 24, 8, 0, 0), FinishDate = new DateTime(2021, 4, 6, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 114, ParentId = 0, Name = "Plumbing", StartDate = new DateTime(2021, 6, 16, 8, 0, 0), FinishDate = new DateTime(2021, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 115, ParentId = 114, Name = "Rough-in plumbing in drywall walls", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 8, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 116, ParentId = 114, Name = "Tie-in fire line riser and set valves", StartDate = new DateTime(2021, 6, 16, 8, 0, 0), FinishDate = new DateTime(2021, 6, 29, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 117, ParentId = 114, Name = "Set plumbing fixtures and trim", StartDate = new DateTime(2021, 8, 11, 8, 0, 0), FinishDate = new DateTime(2021, 8, 31, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 118, ParentId = 114, Name = "Flush, test, and clean piping and fixtures", StartDate = new DateTime(2021, 10, 6, 8, 0, 0), FinishDate = new DateTime(2021, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 119, ParentId = 0, Name = "Electrical", StartDate = new DateTime(2021, 3, 25, 8, 0, 0), FinishDate = new DateTime(2021, 10, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 120, ParentId = 119, Name = "Rough-in electrical in masonry walls", StartDate = new DateTime(2021, 3, 25, 8, 0, 0), FinishDate = new DateTime(2021, 4, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 121, ParentId = 119, Name = "Rough-in electrical in drywall walls", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 8, 10, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 122, ParentId = 119, Name = "Pull wire in conduit and set area transformers", StartDate = new DateTime(2021, 8, 4, 8, 0, 0), FinishDate = new DateTime(2021, 8, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 123, ParentId = 119, Name = "Install and terminate electrical devices", StartDate = new DateTime(2021, 8, 25, 8, 0, 0), FinishDate = new DateTime(2021, 9, 14, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 124, ParentId = 119, Name = "Make electrical terminations for HVAC equipment", StartDate = new DateTime(2021, 8, 25, 8, 0, 0), FinishDate = new DateTime(2021, 8, 26, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 125, ParentId = 119, Name = "Install light fixtures - test and clean", StartDate = new DateTime(2021, 9, 22, 8, 0, 0), FinishDate = new DateTime(2021, 10, 5, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 126, ParentId = 0, Name = "Heating and Ventilating - AC", StartDate = new DateTime(2021, 2, 10, 8, 0, 0), FinishDate = new DateTime(2021, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 127, ParentId = 126, Name = "Set equipment in mechanical room", StartDate = new DateTime(2021, 2, 10, 8, 0, 0), FinishDate = new DateTime(2021, 2, 23, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 128, ParentId = 126, Name = "Rough-in mechanical in masonry walls", StartDate = new DateTime(2021, 3, 25, 8, 0, 0), FinishDate = new DateTime(2021, 4, 21, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 129, ParentId = 126, Name = "Rough-in mechanical in drywall walls", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 7, 27, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 130, ParentId = 126, Name = "Install duct in building chase", StartDate = new DateTime(2021, 7, 14, 8, 0, 0), FinishDate = new DateTime(2021, 8, 3, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 131, ParentId = 126, Name = "Set HVAC trim and test and balance system", StartDate = new DateTime(2021, 9, 22, 8, 0, 0), FinishDate = new DateTime(2021, 10, 19, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 132, ParentId = 0, Name = "Final Clean-up and Occupancy", StartDate = new DateTime(2021, 8, 18, 8, 0, 0), FinishDate = new DateTime(2021, 11, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 133, ParentId = 132, Name = "Install hard tile flooring in common areas", StartDate = new DateTime(2021, 8, 18, 8, 0, 0), FinishDate = new DateTime(2021, 8, 24, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 134, ParentId = 132, Name = "Clean hard tile floors", StartDate = new DateTime(2021, 8, 25, 8, 0, 0), FinishDate = new DateTime(2021, 8, 30, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 135, ParentId = 132, Name = "Remove debris from building and do final clean-up", StartDate = new DateTime(2021, 11, 3, 8, 0, 0), FinishDate = new DateTime(2021, 11, 8, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 136, ParentId = 132, Name = "Substantial completion date", StartDate = new DateTime(2021, 11, 9, 8, 0, 0), FinishDate = new DateTime(2021, 11, 9, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 137, ParentId = 0, Name = "Complete Final Inspections", StartDate = new DateTime(2021, 11, 9, 8, 0, 0), FinishDate = new DateTime(2021, 11, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 138, ParentId = 137, Name = "Complete elevator inspection and certification", StartDate = new DateTime(2021, 11, 9, 8, 0, 0), FinishDate = new DateTime(2021, 11, 11, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 139, ParentId = 137, Name = "Perform architect's inspection", StartDate = new DateTime(2021, 11, 12, 8, 0, 0), FinishDate = new DateTime(2021, 11, 12, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 140, ParentId = 137, Name = "Perform local building agency inspection", StartDate = new DateTime(2021, 11, 15, 8, 0, 0), FinishDate = new DateTime(2021, 11, 15, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 141, ParentId = 137, Name = "Perform Fire Marshal's inspection", StartDate = new DateTime(2021, 11, 16, 8, 0, 0), FinishDate = new DateTime(2021, 11, 16, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 142, ParentId = 0, Name = "Complete punch list items from all inspections", StartDate = new DateTime(2021, 11, 17, 8, 0, 0), FinishDate = new DateTime(2021, 11, 30, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 143, ParentId = 0, Name = "Obtain certificate of occupancy", StartDate = new DateTime(2021, 12, 1, 8, 0, 0), FinishDate = new DateTime(2021, 12, 2, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 144, ParentId = 0, Name = "Issue final completion documents including warranties", StartDate = new DateTime(2021, 12, 1, 8, 0, 0), FinishDate = new DateTime(2021, 12, 1, 17, 0, 0) });
            tasks.Add(new GanttTask { Id = 145, ParentId = 0, Name = "Issue final request for payment", StartDate = new DateTime(2021, 12, 3, 8, 0, 0), FinishDate = new DateTime(2021, 12, 3, 17, 0, 0) });
            tasks[3].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 3 });
            tasks[4].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 4 });
            tasks[5].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 5 });
            tasks[6].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 3 });
            tasks[7].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 7 });
            tasks[8].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 3 });
            tasks[10].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 9 });
            tasks[11].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 8 });
            tasks[12].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 8 });
            tasks[13].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 8 });
            tasks[14].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 8 });
            tasks[15].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 8 });
            tasks[16].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 11 });
            tasks[18].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 3 });
            tasks[19].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 3 });
            tasks[20].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 19 });
            tasks[20].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 20 });
            tasks[21].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 21 });
            tasks[22].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 22 });
            tasks[24].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 21 });
            tasks[24].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 23 });
            tasks[25].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 25 });
            tasks[25].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 23 });
            tasks[26].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 26 });
            tasks[27].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 27 });
            tasks[28].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 27 });
            tasks[29].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 28 });
            tasks[29].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 29 });
            tasks[30].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 30 });
            tasks[32].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 31 });
            tasks[33].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 31 });
            tasks[34].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 33 });
            tasks[35].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 34 });
            tasks[36].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 36 });
            tasks[37].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 35 });
            tasks[38].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 38 });
            tasks[39].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 37 });
            tasks[40].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 40 });
            tasks[41].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 39 });
            tasks[42].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 41 });
            tasks[43].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 42 });
            tasks[44].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 43 });
            tasks[45].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 45 });
            tasks[47].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 44 });
            tasks[47].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 17 });
            tasks[48].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 48 });
            tasks[49].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 48 });
            tasks[50].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 49 });
            tasks[51].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 51 });
            tasks[52].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 52 });
            tasks[54].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 53 });
            tasks[54].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 14 });
            tasks[54].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 15 });
            tasks[54].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 16 });
            tasks[54].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 48 });
            tasks[55].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 48 });
            tasks[56].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 56 });
            tasks[56].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 55 });
            tasks[57].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 57 });
            tasks[58].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 58 });
            tasks[59].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 58 });
            tasks[60].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 58 });
            tasks[61].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 61 });
            tasks[61].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 60 });
            tasks[62].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 62 });
            tasks[63].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 63 });
            tasks[64].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 63 });
            tasks[65].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 63 });
            tasks[66].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 66 });
            tasks[66].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 65 });
            tasks[67].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 67 });
            tasks[68].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 68 });
            tasks[69].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 59 });
            tasks[70].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 59 });
            tasks[71].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 59 });
            tasks[72].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 59 });
            tasks[73].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 70 });
            tasks[73].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 73 });
            tasks[73].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 71 });
            tasks[73].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 72 });
            tasks[74].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 74 });
            tasks[75].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 75 });
            tasks[77].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 64 });
            tasks[77].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 69 });
            tasks[79].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 76 });
            tasks[79].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 14 });
            tasks[80].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 50 });
            tasks[80].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 51 });
            tasks[81].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 78 });
            tasks[82].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 82 });
            tasks[83].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 80 });
            tasks[84].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 82 });
            tasks[85].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 84 });
            tasks[87].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 82 });
            tasks[88].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 12 });
            tasks[88].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 83 });
            tasks[88].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 88 });
            tasks[89].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 89 });
            tasks[90].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 90 });
            tasks[91].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 91 });
            tasks[93].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 82 });
            tasks[94].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[95].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 95 });
            tasks[96].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 82 });
            tasks[98].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 97 });
            tasks[98].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 95 });
            tasks[99].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 99 });
            tasks[99].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 96 });
            tasks[100].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[101].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 95 });
            tasks[101].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 101 });
            tasks[102].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 95 });
            tasks[102].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 102 });
            tasks[103].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 103 });
            tasks[104].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 103 });
            tasks[105].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 100 });
            tasks[106].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 100 });
            tasks[107].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 100 });
            tasks[108].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 108 });
            tasks[110].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 81 });
            tasks[110].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 46 });
            tasks[110].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 13 });
            tasks[111].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 111 });
            tasks[112].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 112 });
            tasks[114].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[115].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 85 });
            tasks[116].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 86 });
            tasks[116].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 115 });
            tasks[116].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 80 });
            tasks[117].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 100 });
            tasks[117].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 116 });
            tasks[117].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 117 });
            tasks[119].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 76 });
            tasks[119].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 15 });
            tasks[120].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[121].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 120 });
            tasks[121].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 101 });
            tasks[122].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 122 });
            tasks[122].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 121 });
            tasks[123].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 122 });
            tasks[123].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 92 });
            tasks[124].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 103 });
            tasks[124].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 123 });
            tasks[126].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 81 });
            tasks[126].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 16 });
            tasks[127].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 76 });
            tasks[128].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[129].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 127 });
            tasks[129].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 128 });
            tasks[129].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 94 });
            tasks[130].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 103 });
            tasks[130].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 130 });
            tasks[130].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 124 });
            tasks[132].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 95 });
            tasks[133].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 133 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 106 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 105 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 107 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 108 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 118 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 125 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 104 });
            tasks[134].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 134 });
            tasks[135].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 135 });
            tasks[137].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 135 });
            tasks[137].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 113 });
            tasks[138].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 135 });
            tasks[138].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 109 });
            tasks[138].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 138 });
            tasks[139].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 139 });
            tasks[140].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 140 });
            tasks[141].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 141 });
            tasks[142].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 142 });
            tasks[143].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 142 });
            tasks[144].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 143 });
            tasks[144].PredecessorLinks.Add(new GanttPredecessorLink() { PredecessorTaskId = 144 });
            tasks[3].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 1 });
            tasks[4].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[4].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 1 });
            tasks[5].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[5].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 4 });
            tasks[6].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 1 });
            tasks[6].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[7].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[7].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 3 });
            tasks[8].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[8].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 3 });
            tasks[11].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 22 });
            tasks[12].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 27 });
            tasks[13].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 20 });
            tasks[14].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 14 });
            tasks[15].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 16 });
            tasks[16].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 18 });
            tasks[17].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 22 });
            tasks[17].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[19].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[20].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[21].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[21].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[22].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 7 });
            tasks[23].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[23].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[25].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[26].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[27].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[28].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[29].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[30].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[31].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 7 });
            tasks[33].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[34].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 12 });
            tasks[35].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[36].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[36].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[37].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[38].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[39].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[40].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[41].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[42].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[43].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[44].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[45].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 19 });
            tasks[46].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[48].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[49].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[50].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[51].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[52].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[53].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 21 });
            tasks[55].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[55].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[56].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[56].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[56].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[57].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[58].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[59].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[60].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[60].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[61].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[61].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[61].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[62].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[63].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[64].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[65].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[65].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[66].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[66].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[66].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[67].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[68].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[69].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[70].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 8 });
            tasks[71].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[72].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[73].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[73].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[73].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[74].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 10 });
            tasks[75].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[76].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[78].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 23 });
            tasks[80].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[81].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 24 });
            tasks[82].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 24 });
            tasks[83].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 26 });
            tasks[84].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 25 });
            tasks[85].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 24 });
            tasks[86].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 25 });
            tasks[88].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 26 });
            tasks[89].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 26 });
            tasks[90].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 26 });
            tasks[91].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 26 });
            tasks[92].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[94].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 28 });
            tasks[95].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 23 });
            tasks[96].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 11 });
            tasks[97].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 28 });
            tasks[99].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 11 });
            tasks[100].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 32 });
            tasks[101].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[102].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[103].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 23 });
            tasks[104].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 23 });
            tasks[105].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 32 });
            tasks[106].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 29 });
            tasks[107].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 11 });
            tasks[108].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 30 });
            tasks[109].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 31 });
            tasks[111].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 19 });
            tasks[112].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 19 });
            tasks[113].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 19 });
            tasks[115].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[116].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[117].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[118].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[120].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[121].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[122].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[123].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[124].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[125].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[127].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[128].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[129].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[130].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[131].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[133].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 25 });
            tasks[134].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 25 });
            tasks[135].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[136].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[138].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 19 });
            tasks[139].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[139].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[140].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[140].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[141].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[141].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 6 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 9 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 13 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 15 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 17 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 23 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 29 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 31 });
            tasks[142].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 32 });
            tasks[143].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            tasks[144].ResourceLinks.Add(new GanttResourceLink() { ResourceId = 2 });
            #endregion
            return tasks;
        }
        List<GanttResource> CreateResources() {
            var resources = new List<GanttResource>();
            #region Data generation
            resources.Add(new GanttResource() { Id = 1, Name = "G.C. General Management" });
            resources.Add(new GanttResource() { Id = 2, Name = "G.C. Project Management" });
            resources.Add(new GanttResource() { Id = 3, Name = "G.C. Procurement" });
            resources.Add(new GanttResource() { Id = 4, Name = "G.C. Scheduler" });
            resources.Add(new GanttResource() { Id = 5, Name = "G.C. Accounting" });
            resources.Add(new GanttResource() { Id = 6, Name = "G.C. Superintendent" });
            resources.Add(new GanttResource() { Id = 7, Name = "G.C. Survey Crew" });
            resources.Add(new GanttResource() { Id = 8, Name = "G.C. Rough Carpenter Crew" });
            resources.Add(new GanttResource() { Id = 9, Name = "G.C. Labor Crew" });
            resources.Add(new GanttResource() { Id = 10, Name = "G.C. Concrete Crew" });
            resources.Add(new GanttResource() { Id = 11, Name = "G.C. Finish Carpenter Crew" });
            resources.Add(new GanttResource() { Id = 12, Name = "Site Grading Contractor" });
            resources.Add(new GanttResource() { Id = 13, Name = "Plumbing Contractor" });
            resources.Add(new GanttResource() { Id = 14, Name = "Plumbing Contractor Management" });
            resources.Add(new GanttResource() { Id = 15, Name = "Electric Contractor" });
            resources.Add(new GanttResource() { Id = 16, Name = "Electric Contractor Management" });
            resources.Add(new GanttResource() { Id = 17, Name = "HVAC Contractor" });
            resources.Add(new GanttResource() { Id = 18, Name = "HVAC Contractor Management" });
            resources.Add(new GanttResource() { Id = 19, Name = "Elevator Contractor" });
            resources.Add(new GanttResource() { Id = 20, Name = "Elevator Contractor Management" });
            resources.Add(new GanttResource() { Id = 21, Name = "Steel Erection Contractor" });
            resources.Add(new GanttResource() { Id = 22, Name = "Steel Erection Contractor Management" });
            resources.Add(new GanttResource() { Id = 23, Name = "Drywall Contractor" });
            resources.Add(new GanttResource() { Id = 24, Name = "Masonry Contractor" });
            resources.Add(new GanttResource() { Id = 25, Name = "Tile Contractor" });
            resources.Add(new GanttResource() { Id = 26, Name = "Roofing Contractor" });
            resources.Add(new GanttResource() { Id = 27, Name = "Roofing Contractor Management" });
            resources.Add(new GanttResource() { Id = 28, Name = "Window Contractor" });
            resources.Add(new GanttResource() { Id = 29, Name = "Carpet Contractor" });
            resources.Add(new GanttResource() { Id = 30, Name = "Landscape Contractor" });
            resources.Add(new GanttResource() { Id = 31, Name = "Paving Contractor" });
            resources.Add(new GanttResource() { Id = 32, Name = "Painting Contractor" });
            #endregion
            return resources;
        }
        List<GanttResourceLink> CreateResourceLinks() {
            var resourcesLinks = new List<GanttResourceLink>();
            #region Data generation
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 1, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 1, AllocationPercentage = 0.25 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.25 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 4, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 1, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 3, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 3, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 22, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 27, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 20, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 14, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 16, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 18, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 22, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 7, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 7, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 12, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 19, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 0.75 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 0.75 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 21, AllocationPercentage = 0.2 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.2 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.2 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.2 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 8, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 10, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 23, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 24, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 24, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 26, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 25, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 24, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 25, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 26, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 26, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 26, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 26, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 28, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 23, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 11, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 28, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 11, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 32, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 23, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 23, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 32, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 29, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 11, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 30, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 31, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 19, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 19, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 19, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 25, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 25, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 19, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.5 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 6, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 9, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 13, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 15, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 17, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 23, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 29, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 31, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 32, AllocationPercentage = 0.11 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 1 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 2, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 5, AllocationPercentage = 0.33 });
            resourcesLinks.Add(new GanttResourceLink() { ResourceId = 1, AllocationPercentage = 0.33 });
            #endregion
            return resourcesLinks;
        }
    }
}
