using DevExpress.Mvvm;
using System.ComponentModel;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.Commands {
    public class POCOCommandsViewModel_RuntimeGeneratedCode : POCOCommandsViewModel, INotifyPropertyChanged {
        DelegateCommand _SaveCommand;
        public DelegateCommand SaveCommand {
            get {
                return _SaveCommand ?? 
                    (_SaveCommand = new DelegateCommand(Save, CanSave));
            }
        }

        DelegateCommand<string> _OpenCommand;
        public DelegateCommand<string> OpenCommand {
            get {
                return _OpenCommand ?? 
                    (_OpenCommand = new DelegateCommand<string>(Open, CanOpen));
            }
        }

        #region properties
        public override bool CanExecuteSaveCommand {
            get { return base.CanExecuteSaveCommand; }
            set {
                if(base.CanExecuteSaveCommand == value)
                    return;
                base.CanExecuteSaveCommand = value;
                RaisePropertyChanged("CanExecuteSaveCommand");
            }
        }

        public override string FileName {
            get { return base.FileName; }
            set {
                if(base.FileName == value)
                    return;
                base.FileName = value;
                RaisePropertyChanged("FileName");
            }
        }
        #endregion

        #region INotifyPropertyChanged implementation
        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propertyName) {
            var handler = PropertyChanged;
            if(handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}
