Imports System.ComponentModel.DataAnnotations
Imports DevExpress.Mvvm.DataAnnotations

Namespace TreeListDemo

    <MetadataType(GetType(DataAnnotationsElement3Metadata))>
    Public Class DataAnnotationsElement3_FluentAPI

        Public Property ID As Integer

        Public Property ParentID As Integer

        Public Property LastName As String

        Public Property FirstName As String

        Public Property Gender As Gender

        Public Property BirthDate As Date

        Public Property Address As String

        Public Property City As String

        Public Property Group As String

        Public Property Title As String

        Public Property HireDate As Date

        Public Property Salary As Decimal

        Public Property Phone As String

        Public Property Email As String

        Public Overrides Function ToString() As String
            Return "Bands Layout (Fluent API)"
        End Function
    End Class

    Public Class DataAnnotationsElement3Metadata
        Implements IMetadataProvider(Of DataAnnotationsElement3_FluentAPI)

        Private Sub BuildMetadata(ByVal builder As MetadataBuilder(Of DataAnnotationsElement3_FluentAPI)) Implements IMetadataProvider(Of DataAnnotationsElement3_FluentAPI).BuildMetadata
            builder.Property(Function(p) p.ID).NotAutoGenerated()
            builder.Property(Function(p) p.ParentID).NotAutoGenerated()
            builder.Property(Function(p) p.FirstName).DisplayName("First name")
            builder.Property(Function(p) p.LastName).DisplayName("Last name")
            builder.Property(Function(p) p.BirthDate).DisplayName("Birth date")
            builder.Group("Personal").ContainsProperty(Function(p) p.FirstName).ContainsProperty(Function(p) p.LastName).ContainsProperty(Function(p) p.Gender).ContainsProperty(Function(p) p.BirthDate)
            builder.Property(Function(p) p.Address).DisplayShortName("Address1")
            builder.Property(Function(p) p.City).DisplayShortName("Address2")
            builder.Group("Address").ContainsProperty(Function(p) p.Address).ContainsProperty(Function(p) p.City)
            builder.Property(Function(p) p.HireDate).DisplayName("Hire date")
            builder.[Property](Function(p) p.Salary).CurrencyDataType()
            builder.Group("Job").ContainsProperty(Function(p) p.Group).ContainsProperty(Function(p) p.Title).ContainsProperty(Function(p) p.HireDate).ContainsProperty(Function(p) p.Salary)
            builder.[Property](Function(p) p.Phone).PhoneNumberDataType()
            builder.Group("Contact").ContainsProperty(Function(p) p.Phone).ContainsProperty(Function(p) p.Email)
        End Sub
    End Class
End Namespace
