Imports System.ComponentModel.DataAnnotations
Imports DevExpress.Mvvm.DataAnnotations

Namespace TreeListDemo

    <MetadataType(GetType(DataAnnotationsElement4Metadata))>
    Public Class DataAnnotationsElement4_FluentAPI

        Public Property ID As Integer

        Public Property ParentID As Integer

        Public Property ProductCategory As CategoryData

        Public Property ProductName As String

        Public Property CustomerName As String

        Public Property OrderDate As Date

        Public Property Quantity As Integer

        Public Property Price As Decimal

        Public Property IsReady As Boolean

        Public Overrides Function ToString() As String
            Return "Nested Bands Layout (Fluent API)"
        End Function
    End Class

    Public Class DataAnnotationsElement4Metadata
        Implements IMetadataProvider(Of DataAnnotationsElement4_FluentAPI)

        Private Sub BuildMetadata(ByVal builder As MetadataBuilder(Of DataAnnotationsElement4_FluentAPI)) Implements IMetadataProvider(Of DataAnnotationsElement4_FluentAPI).BuildMetadata
            Dim groupBuilder = builder.TableLayout()
            builder.Property(Function(p) p.ID).DisplayName("Id").NotAutoGenerated().NotEditable()
            builder.Property(Function(p) p.ParentID).DisplayName("ParentID").NotAutoGenerated().NotEditable()
            builder.Property(Function(p) p.ProductCategory).DisplayName("Category").NotEditable()
            builder.Property(Function(p) p.ProductName).DisplayName("Name").NotEditable()
            groupBuilder.Group("Product Details").ContainsProperty(Function(p) p.ProductCategory).ContainsProperty(Function(p) p.ProductName)
            builder.Property(Function(p) p.CustomerName).DisplayName("Customer").NotEditable()
            builder.Property(Function(p) p.OrderDate).DisplayName("Date")
            groupBuilder.GroupContainer("Order Details").Group("Main").ContainsProperty(Function(p) p.CustomerName).ContainsProperty(Function(p) p.OrderDate)
            builder.[Property](Function(p) p.Price).CurrencyDataType()
            builder.Property(Function(p) p.IsReady).DisplayName("Is ready")
            groupBuilder.GroupContainer("Order Details").Group("Status").ContainsProperty(Function(p) p.Quantity).ContainsProperty(Function(p) p.Price).ContainsProperty(Function(p) p.IsReady)
        End Sub
    End Class
End Namespace
