Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel
Imports DevExpress.Mvvm.DataAnnotations

Namespace TreeListDemo

    <MetadataType(GetType(DataAnnotationsElement2Metadata))>
    Public Class DataAnnotationsElement2_FluentAPI

        Public Property ID As Integer

        Public Property ParentID As Integer

        Public Property Employer As String

        Public Property FirstName As String

        Public Property LastName As String

        Public ReadOnly Property FullName As String
            Get
                Return FirstName & " " & LastName
            End Get
        End Property

        Public Property Gender As Gender

        Public Property Age As Integer

        Public Property SSN As String

        Public Overrides Function ToString() As String
            Return "Attribute support (Fluent API)"
        End Function
    End Class

    Public Class DataAnnotationsElement2Metadata
        Implements IMetadataProvider(Of DataAnnotationsElement2_FluentAPI)

        Private Sub BuildMetadata(ByVal builder As MetadataBuilder(Of DataAnnotationsElement2_FluentAPI)) Implements IMetadataProvider(Of DataAnnotationsElement2_FluentAPI).BuildMetadata
            builder.Property(Function(p) p.ID).NotAutoGenerated()
            builder.Property(Function(p) p.ParentID).NotAutoGenerated()
            builder.Property(Function(p) p.Employer).NotEditable()
            builder.Property(Function(p) p.FirstName).DisplayName("First name").Required()
            builder.Property(Function(p) p.LastName).DisplayName("Last name").Required()
            builder.Property(Function(p) p.FullName).DisplayName("Full name")
            builder.Property(Function(p) p.SSN).ReadOnly()
        End Sub
    End Class
End Namespace
