Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/BindingIndividualSeries.xaml"), CodeFile("Modules/DataBinding/BindingIndividualSeriesViewModel.(cs)"), CodeFile("DataModels/DevAVSalesData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class BindingIndividualSeriesDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
