Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/Colorizer.xaml"), CodeFiles("DataModels/HPIStatistics.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class ColorizerDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
