Imports System.Windows
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/DataFiltering.xaml"), CodeFile("Modules/DataBinding/DataFiltering.xaml.(cs)"), CodeFile("Modules/DataBinding/DataFilteringViewModels.(cs)"), CodeFile("DataModels/DevAVBranchesSales.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class DataFilteringDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Overloads Sub ChartsDemoModule_ModuleLoaded(ByVal sender As Object, ByVal e As RoutedEventArgs)
            chart.Animate()
            chart.AnimationMode = ChartAnimationMode.OnDataChanged
        End Sub

        Private Sub ChartsDemoModule_ModuleUnLoaded(ByVal sender As Object, ByVal e As RoutedEventArgs)
            While filterBehavior.Fields.Count > 0
                filterBehavior.Fields.RemoveAt(0)
            End While
        End Sub
    End Class
End Namespace
