Imports System
Imports System.Globalization
Imports System.Windows.Data
Imports DevExpress.Mvvm
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/DataGridCharting.xaml"), CodeFile("Modules/DataBinding/DataGridCharting.xaml.(cs)"), CodeFile("DataModels/SalesProductData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class DataGridChartingDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Public Enum AggregateType
        Average = 1
        Min = 2
        Max = 3
        Sum = 4
    End Enum

    Public Class AggregateTypeToAggregateFunctionConverter
        Implements IValueConverter

        Private Function Convert(ByVal value As Object, ByVal targetType As Type, ByVal parameter As Object, ByVal culture As CultureInfo) As Object Implements IValueConverter.Convert
            Dim aType As EnumMemberInfo = TryCast(value, EnumMemberInfo)
            If aType Is Nothing Then Return AggregateFunction.None
            Return CType(System.Convert.ToInt32(aType.Id), AggregateFunction)
        End Function

        Private Function ConvertBack(ByVal value As Object, ByVal targetType As Type, ByVal parameter As Object, ByVal culture As CultureInfo) As Object Implements IValueConverter.ConvertBack
            Return Nothing
        End Function
    End Class
End Namespace
