Imports System.Windows
Imports System.Windows.Controls
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/MvvmStyleBinding.xaml"), CodeFile("Modules/DataBinding/MvvmStyleBinding.xaml.(cs)"), CodeFile("Modules/DataBinding/MvvmStyleBindingViewModel.(cs)"), CodeFile("DataModels/ExtremeWeatherData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class MvvmStyleBindingDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Public Class WeatherTemplateSelector
        Inherits DataTemplateSelector

        Public Property AverageTemplate As DataTemplate

        Public Property MinMaxTemplate As DataTemplate

        Public Overrides Function SelectTemplate(ByVal item As Object, ByVal container As DependencyObject) As DataTemplate
            Dim weatherItem As WeatherItem = TryCast(item, WeatherItem)
            If weatherItem IsNot Nothing Then Return If(weatherItem.IsAverageWeather, AverageTemplate, MinMaxTemplate)
            Return Nothing
        End Function
    End Class
End Namespace
