Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/DataBinding/SeriesTemplateBinding.xaml"), CodeFile("Modules/DataBinding/SeriesTemplateBindingViewModel.(cs)"), CodeFile("Modules/DataBinding/StandardDeviationCustomAggregateFunction.(cs)"), CodeFile("DataModels/DevAVSalesData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class SeriesTemplateBindingDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
