Imports DevExpress.Mvvm
Imports DevExpress.Mvvm.DataAnnotations
Imports System.ComponentModel

' This class demonstrates the code that will be generated by the POCO mechanism at runtime
Namespace MVVMDemo.POCOViewModels

    <POCOViewModel(ImplementIDataErrorInfo:=True)>
    Public Class DataErrorInfoViewModel_RuntimeGeneratedCode
        Inherits DataErrorInfoViewModel
        Implements IDataErrorInfo, INotifyPropertyChanged

        Private ReadOnly Property [Error] As String Implements IDataErrorInfo.[Error]
            Get
                Return String.Empty
            End Get
        End Property

        Private ReadOnly Property Item(ByVal columnName As String) As String Implements IDataErrorInfo.Item
            Get
                Return IDataErrorInfoHelper.GetErrorText(Me, columnName)
            End Get
        End Property

#Region "properties and commands"
        Public Overrides Property UserName As String
            Get
                Return MyBase.UserName
            End Get

            Set(ByVal value As String)
                If Equals(MyBase.UserName, value) Then Return
                MyBase.UserName = value
                RaisePropertyChanged("UserName")
            End Set
        End Property

        Private _RegisterCommand As DelegateCommand

        Public ReadOnly Property RegisterCommand As DelegateCommand
            Get
                Return If(_RegisterCommand, Function()
                    _RegisterCommand = New DelegateCommand(AddressOf Register, AddressOf CanRegister)
                    Return _RegisterCommand
                End Function())
            End Get
        End Property

#End Region
#Region "INotifyPropertyChanged implementation"
        Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

        Private Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim handler = PropertyChangedEvent
            If handler IsNot Nothing Then handler(Me, New PropertyChangedEventArgs(propertyName))
        End Sub
#End Region
    End Class
End Namespace
