Imports DevExpress.Mvvm
Imports System.ComponentModel

' This class demonstrates the code that will be generated by the POCO mechanism at runtime
Namespace MVVMDemo.POCOViewModels

    Public Class LoginViewModel_RuntimeGeneratedCode
        Inherits LoginViewModel
        Implements INotifyPropertyChanged

        Public Overrides Property UserName As String
            Get
                Return MyBase.UserName
            End Get

            Set(ByVal value As String)
                If Equals(MyBase.UserName, value) Then Return
                MyBase.UserName = value
                RaisePropertyChanged("UserName")
            End Set
        End Property

        Public Overrides Property Status As String
            Get
                Return MyBase.Status
            End Get

            Set(ByVal value As String)
                If Equals(MyBase.Status, value) Then Return
                MyBase.Status = value
                RaisePropertyChanged("Status")
            End Set
        End Property

        Private _LoginCommand As DelegateCommand

        Public ReadOnly Property LoginCommand As DelegateCommand
            Get
                Return If(_LoginCommand, Function()
                    _LoginCommand = New DelegateCommand(AddressOf Login, AddressOf CanLogin)
                    Return _LoginCommand
                End Function())
            End Get
        End Property

        Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

        Private Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim handler = PropertyChangedEvent
            If handler IsNot Nothing Then handler(Me, New PropertyChangedEventArgs(propertyName))
        End Sub
    End Class
End Namespace
