using DevExpress.Xpf.Core;
using DevExpress.Xpf.DemoBase;

namespace CommonDemo.TabControl.WebBrowser {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.WebBrowser/MainView.xaml",
        "Modules/TabControl.WebBrowser/MainViewModel.(cs)",
        "Modules/TabControl.WebBrowser/WebBrowserView.xaml",
        "Modules/TabControl.WebBrowser/WebBrowserViewModel.(cs)",
        "Modules/TabControl.WebBrowser/WebBrowserWindow.xaml")]
    public partial class MainView : DemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
