using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/SeriesTypes/Lines/LinesDemo.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/LineTab.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/ScatterLineTab.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/StepLineTab.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/SplineTab.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/StackedLineTab.xaml"),
     CodeFile("Modules/SeriesTypes/Lines/FullStackedLineTab.xaml"),
     CodeFile("Modules/SeriesTypes/CustomMarkerModel.xaml"),
     CodeFile("DataModels/DevAVBranchesSales.(cs)"),
     CodeFile("DataModels/PowerConsumption.(cs)"),
     CodeFile("CommonViewModels.(cs)"),
     CodeFile("DataModels/DevAVSalesByLast10Years.(cs)"),
     CodeFile("DataModels/FuelPrices.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class LinesDemo : ChartsDemoModule {
        public LinesDemo() {
            InitializeComponent();
        }
    }
}
