using System.Windows;
using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.Wizard.WpfTour {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Wizard.WpfTour/MainView.xaml",
        "Modules/Wizard.WpfTour/MainViewModel.(cs)",
        "Modules/Wizard.WpfTour/WizardViewModel.(cs)",
        "Modules/Wizard.WpfTour/Templates.xaml")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
