Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.Wizard.WpfTour

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Wizard.WpfTour/MainView.xaml", "Modules/Wizard.WpfTour/MainViewModel.(cs)", "Modules/Wizard.WpfTour/WizardViewModel.(cs)", "Modules/Wizard.WpfTour/Templates.xaml")>
    Public Partial Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
