using DevExpress.Mvvm;
using System.ComponentModel;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.AsyncCommands {
    public class AsyncPOCOCommandsViewModel_RuntimeGeneratedCode : AsyncPOCOCommandsViewModel, INotifyPropertyChanged {
        AsyncCommand _CalculateCommand;
        public AsyncCommand CalculateCommand {
            get {
                return _CalculateCommand ?? 
                    (_CalculateCommand = new AsyncCommand(Calculate));
            }
        }

        #region properties
        public override int Progress {
            get { return base.Progress; }
            set {
                if(base.Progress == value)
                    return;
                base.Progress = value;
                RaisePropertyChanged("Progress");
            }
        }
        #endregion    

        #region INotifyPropertyChanged implementation
        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propertyName) {
            var handler = PropertyChanged;
            if(handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}
