Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/ChartElements/Titles/Titles.xaml"), CodeFile("Modules/ChartElements/Titles/XYDiagramTitlesTab.xaml"), CodeFile("Modules/ChartElements/Titles/XYDiagramTitlesTab.xaml.(cs)"), CodeFile("Modules/ChartElements/Titles/SimpleDiagramTitlesTab.xaml"), CodeFile("Modules/ChartElements/Titles/SimpleDiagramTitlesTab.xaml.(cs)"), CodeFile("DataModels/DevAVSalesData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class TitlesDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
