Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.TabControl.PinnedTabs

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TabControl.PinnedTabs/MainView.xaml", "Modules/TabControl.PinnedTabs/MainViewModel.(cs)")>
    Public Partial Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
