using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/Titles/Titles.xaml"),
     CodeFile("Modules/ChartElements/Titles/XYDiagramTitlesTab.xaml"),
     CodeFile("Modules/ChartElements/Titles/XYDiagramTitlesTab.xaml.(cs)"),
     CodeFile("Modules/ChartElements/Titles/SimpleDiagramTitlesTab.xaml"),
     CodeFile("Modules/ChartElements/Titles/SimpleDiagramTitlesTab.xaml.(cs)"),
     CodeFile("DataModels/DevAVSalesData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class TitlesDemo : ChartsDemoModule {
        public TitlesDemo() {
            InitializeComponent();
        }
    }
}
