using System.Collections.Generic;
using DevExpress.Mvvm;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Mvvm.POCO;
using DevExpress.Xpf.TreeMap;
using System.Xml;
using DevExpress.Xpf.DemoBase;
using System.Windows;

namespace TreeMapDemo {
    [CodeFile("Modules/TreeMap/Grouping.xaml")]
    [CodeFile("Modules/TreeMap/Grouping.xaml.(cs)")]
    [NoAutogeneratedCodeFiles]
    public partial class Grouping : TreeMapDemoModule {
        public Grouping() {
            InitializeComponent();
        }
    }

    [POCOViewModel]
    public class GroupingViewModel : ViewModelBase {
        static GroupingViewModel instance;

        public static GroupingViewModel Instance {
            get {
                if(instance == null)
                    instance = ViewModelSource.Create(() => new GroupingViewModel());
                return instance;
            }
        }

        public virtual XmlDocument BillionairesInfos { get; set; }
        public virtual List<string> ValueMembers { get; set; }
        public virtual List<GroupDefinitionSettings> GroupDefinitionSettings { get; set; }
        public virtual GroupDefinitionSettings GroupDefinition { get; set; }

        protected GroupingViewModel() {
            BillionairesInfos = DataLoader.LoadXmlDocumentFromResources("/Data/Billionares.xml");
            GroupDefinitionSettings = GetGroupDefinitionSettings();
            GroupDefinition = GroupDefinitionSettings[1];
        }

        List<GroupDefinitionSettings> GetGroupDefinitionSettings() {
            GroupDefinitionCollection GroupByResidence = new GroupDefinitionCollection();
            GroupByResidence.Add(new TreeMapGroupDefinition() { GroupDataMember = "Residence" });
            GroupDefinitionCollection GroupByAgeCategory = new GroupDefinitionCollection();
            GroupByAgeCategory.Add(new TreeMapGroupDefinition() { GroupDataMember = "AgeCategory" });
            GroupDefinitionCollection GroupByResidenceAndAgeCategory = new GroupDefinitionCollection();
            GroupByResidenceAndAgeCategory.Add(new TreeMapGroupDefinition() { GroupDataMember = "Residence" });
            GroupByResidenceAndAgeCategory.Add(new TreeMapGroupDefinition() { GroupDataMember = "AgeCategory" });
            return new List<GroupDefinitionSettings>() {
                new GroupDefinitionSettings() { CollectionGroupDefinitionName = "Without Grouping", ColorizeGroups = false, CollectionGroupDefinition = new GroupDefinitionCollection() },
                new GroupDefinitionSettings() { CollectionGroupDefinitionName = "Group By Residence", ColorizeGroups = true, CollectionGroupDefinition = GroupByResidence, 
                                                LegendVisibility = Visibility.Visible, LegendTitle = "Net Worth by Residence,\nin billions of dollars" },
                new GroupDefinitionSettings() { CollectionGroupDefinitionName = "Group By Age Category", ColorizeGroups = true, CollectionGroupDefinition = GroupByAgeCategory, 
                                                LegendVisibility = Visibility.Visible, LegendTitle = "Net Worth by Age Category,\nin billions of dollars" },
                new GroupDefinitionSettings() { CollectionGroupDefinitionName = "Group By Residence And Age Category", ColorizeGroups = true, CollectionGroupDefinition = GroupByResidenceAndAgeCategory, LegendVisibility = Visibility.Collapsed }
            };
        }
    }

    public class GroupDefinitionSettings {
        public GroupDefinitionCollection CollectionGroupDefinition { get; set; }
        public string CollectionGroupDefinitionName { get; set; }
        public bool ColorizeGroups { get; set; }
        public Visibility LegendVisibility { get; set; }
        public string LegendTitle { get; set; }

        public override string ToString() {
            return CollectionGroupDefinitionName;
        }
    }
}
