Imports DevExpress.Xpf.Core
Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.Wizard.Properties

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Wizard.Properties/MainView.xaml", "Modules/Wizard.Properties/MainView.xaml.(cs)")>
    Public Partial Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub wizard_Cancel(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs)
            ThemedMessageBox.Show("Cancel Button clicked!")
            e.Cancel = True
        End Sub

        Private Sub wizard_Finish(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs)
            ThemedMessageBox.Show("Finish Button clicked!")
            e.Cancel = True
        End Sub
    End Class
End Namespace
