using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/ChartElements/Panes/PanesDemo.xaml"),
     CodeFile("Modules/ChartElements/Panes/LinearPaneLayoutTab.xaml"),
     CodeFile("Modules/ChartElements/Panes/GridPaneLayoutTab.xaml"),
     CodeFile("DataModels/WebSitePerformanceIndicator.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class PanesDemo : ChartsDemoModule {
        public PanesDemo() {
            InitializeComponent();
        }
    }
}
