using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {

    [CodeFile("Modules/DataAnalysis/ErrorBars.xaml"),
     CodeFile("DataModels/ErrorBarsData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class ErrorBarsDemo : ChartsDemoModule {
        public ErrorBarsDemo() {
            InitializeComponent();
        }
    }

}
