using System;
using System.Windows;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {

    [CodeFile("Modules/DataAnalysis/FinancialIndicators.xaml"),
     CodeFile("Modules/DataAnalysis/FinancialIndicators.xaml.(cs)"),
     CodeFile("DataModels/FinancialDataGenerator.(cs)"),
     CodeFile("DataModels/FinancialDataPoint.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class FinancialIndicatorsDemo : ChartsDemoModule {
        public FinancialIndicatorsDemo() {
            InitializeComponent();
            this.chart.DataSource = FinancialDataGenerator.Generate();
        }

        void chart_BoundDataChanged(object sender, RoutedEventArgs e) {
            this.fibonacciArcs.Argument1 = DateTime.Now.Date.AddDays(-165);
            this.fibonacciArcs.Argument2 = DateTime.Now.Date.AddDays(-140);
            this.fibonacciFans.Argument1 = DateTime.Now.Date.AddDays(-66);
            this.fibonacciFans.Argument2 = DateTime.Now.Date.AddDays(-49);
            DateTime max = DateTime.Now.Date.AddDays(2);
            DateTime min = max.AddDays(-185);
            xVisualRange.SetMinMaxValues(min, max);
        }
    }
}
