using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/SeriesTypes/Areas/AreasDemo.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/AreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/StepAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/SplineAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/StackedAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/StackedStepAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/StackedSplineAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/FullStackedAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/FullStackedStepAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/FullStackedSplineAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/RangeAreaTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/Area3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/StackedArea3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/Areas/FullStackedArea3DTab.xaml"),
     CodeFile("Modules/SeriesTypes/CustomMarkerModel.xaml"),
     CodeFile("DataModels/OutsideVendorCosts.(cs)"),
     CodeFile("DataModels/DevAVBranchesSales.(cs)"),
     CodeFile("DataModels/CommentsData.(cs)"),
     CodeFile("DataModels/OilPrices.(cs)"),
     CodeFile("DataModels/DevAVSalesByLast10Years.(cs)"),
     CodeFile("DataModels/FuelPrices.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class AreasDemo : ChartsDemoModule {
        public AreasDemo() {
            InitializeComponent();
        }
    }
}
