using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/BindingIndividualSeries.xaml"),
     CodeFile("Modules/DataBinding/BindingIndividualSeriesViewModel.(cs)"),
     CodeFile("DataModels/DevAVSalesData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class BindingIndividualSeriesDemo : ChartsDemoModule {
        public BindingIndividualSeriesDemo() {
            InitializeComponent();
        }
    }
}
