using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/Colorizer.xaml"),
     CodeFiles("DataModels/HPIStatistics.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class ColorizerDemo : ChartsDemoModule {
        public ColorizerDemo() {
            InitializeComponent();
        }
    }

}
