using System.Windows;
using DevExpress.Xpf.Charts;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/DataFiltering.xaml"),
     CodeFile("Modules/DataBinding/DataFiltering.xaml.(cs)"),
     CodeFile("Modules/DataBinding/DataFilteringViewModels.(cs)"),
     CodeFile("DataModels/DevAVBranchesSales.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class DataFilteringDemo : ChartsDemoModule {
        public DataFilteringDemo() {
            InitializeComponent();
        }
        void ChartsDemoModule_ModuleLoaded(object sender, RoutedEventArgs e) {
            this.chart.Animate();
            this.chart.AnimationMode = ChartAnimationMode.OnDataChanged;
        }
        void ChartsDemoModule_ModuleUnLoaded(object sender, RoutedEventArgs e) {
            while (filterBehavior.Fields.Count > 0)  
                filterBehavior.Fields.RemoveAt(0);
        }
    }
}
