using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/SeriesTemplateBinding.xaml"),
     CodeFile("Modules/DataBinding/SeriesTemplateBindingViewModel.(cs)"),
     CodeFile("Modules/DataBinding/StandardDeviationCustomAggregateFunction.(cs)"),
     CodeFile("DataModels/DevAVSalesData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class SeriesTemplateBindingDemo : ChartsDemoModule {

        public SeriesTemplateBindingDemo() {
            InitializeComponent();
        }
    }
}
