using System;
using System.Globalization;
using System.Windows;
using System.Windows.Data;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/TopNAndOthers.xaml"),
     CodeFile("Modules/DataBinding/TopNAndOthers.xaml.(cs)"),
     CodeFile("DataModels/CountriesAreaData.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class TopNAndOthersDemo : ChartsDemoModule {
        public TopNAndOthersDemo() {
            InitializeComponent();
        }
        void AnimateChart(object sender, RoutedEventArgs e) {
            this.chart.Animate();
        }
    }

    public class SelectedIndexToVisibilityConverter : IValueConverter {
        object IValueConverter.Convert(object value, Type targetType, object parameter, CultureInfo culture) {
            try {
                int index = Convert.ToInt32(value);
                int expectedIndex = Convert.ToInt32(parameter);
                if (index == expectedIndex)
                    return Visibility.Visible;
            }
            catch { }
            return Visibility.Collapsed;
        }
        object IValueConverter.ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) {
            return value;
        }
    }
}
