Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo

    <CodeFile("Modules/SeriesTypes/PolarAndRadar/PolarAndRadarDemo.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/PolarAreaTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/PolarPointTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/PolarLineTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/ScatterPolarLineTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/PolarRangeAreaTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/RadarAreaTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/RadarPointTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/RadarLineTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/ScatterRadarLineTab.xaml"), CodeFile("Modules/SeriesTypes/PolarAndRadar/RadarRangeAreaTab.xaml"), CodeFile("CommonViewModels.(cs)"), CodeFile("DataModels/WindRoseData.(cs)"), CodeFile("DataModels/LondonTemperatureData.(cs)"), NoAutogeneratedCodeFiles>
    Public Partial Class PolarAndRadarDemo
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
