using DevExpress.Mvvm.DataAnnotations;
using System.ComponentModel.DataAnnotations;

namespace GridDemo {
    [MetadataType(typeof(DataAnnotationsElement2Metadata))]
    public class DataAnnotationsElement2_FluentAPI {
        public int ID { get; set; }
        public string Employer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get { return FirstName + " " + LastName; } }
        public int Age { get; set; }
        public string SSN { get; set; }
        public string Department { get; set; }
    }

    public static class DataAnnotationsElement2Metadata {
        public static void BuildMetadata(MetadataBuilder<DataAnnotationsElement2_FluentAPI> builder) {
            builder.Property(p => p.ID).NotAutoGenerated();
            builder.Property(p => p.Employer).NotEditable();
            builder.Property(p => p.FirstName).DisplayName("First name").Required();
            builder.Property(p => p.LastName).DisplayName("Last name").Required();
            builder.Property(p => p.FullName).DisplayName("Full name");
            builder.Property(p => p.Age).DisplayFormatString("d2", applyDisplayFormatInEditMode:true);
            builder.Property(p => p.SSN).ReadOnly();
            builder.Property(p => p.Department).NullDisplayText("Department not set");
        }
    }
}
