using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/Highlighted/RealTime3DChartDemo.xaml"),
     CodeFile("Modules/Highlighted/RealTime3DChartDemoViewModel.(cs)"),
     CodeFile("DataModels/RealTime3DDataGenerator.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class RealTime3DChartDemo : ChartsDemoModule {
        public RealTime3DChartDemo() {
            InitializeComponent();
        }
    }
}
