using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/Highlighted/TornadoChart.xaml"),
     CodeFile("Modules/Highlighted/TornadoChart.xaml.(cs)"),
     CodeFile("Modules/Highlighted/TornadoChartViewModel.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class TornadoChartDemo : ChartsDemoModule {
        public TornadoChartDemo() {
            InitializeComponent();
        }
    }
}
