using System.Windows;
using DevExpress.Xpf.Core.Native;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [CodeFile("Modules/DataBinding/DataAggregation/DataAggregation.xaml"),
     CodeFile("Modules/DataBinding/DataAggregation/DataAggregation.xaml.(cs)"),
     CodeFile("DataModels/DevAVSalesData.(cs)"),
     CodeFile("DataModels/DateTimeArgumentData.(cs)"),
     CodeFile("DataModels/NumericArgumentData.(cs)"),
     CodeFile("Modules/DataBinding/DataAggregation/DateTimeDataAggregationTab.xaml"),
     CodeFile("Modules/DataBinding/DataAggregation/DateTimeDataAggregationTab.xaml.(cs)"),
     CodeFile("Modules/DataBinding/DataAggregation/NumericDataAggregationTab.xaml"),
     CodeFile("Modules/DataBinding/DataAggregation/NumericDataAggregationTab.xaml.(cs)"),
     CodeFile("Modules/DataBinding/DataAggregation/QualitativeDataAggregationTab.xaml"),
     CodeFile("Modules/DataBinding/DataAggregation/QualitativeDataAggregationTab.xaml.(cs)"),
     CodeFile("Modules/DataBinding/DataAggregation/TimeSpanDataAggregationTab.xaml"),
     CodeFile("Modules/DataBinding/DataAggregation/TimeSpanDataAggregationTab.xaml.(cs)"),
     CodeFile("Modules/DataBinding/StandardDeviationCustomAggregateFunction.(cs)"),
     NoAutogeneratedCodeFiles]
    public partial class DataAggregationDemo : ChartsDemoModule {
        public DataAggregationDemo() {
            InitializeComponent();
        }

        void OnTabItemLoaded(object sender, RoutedEventArgs e) {
            NotCachedTabbedModuleViewModel tabbedViewModel = (NotCachedTabbedModuleViewModel)DataContext;
            TabItemModule module = (TabItemModule)LayoutHelper.FindElementByType(this, sender.GetType());
            tabbedViewModel.Options = module.Options;
        }
    }
}
