#pragma checksum "..\..\..\..\Modules\EnumItemsSource\ListBoxEditView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0685B7473DE19CD0A6A33C93D7D2A585933F7ADEE10AE2FE45F7202DD21503D7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Xpf.DXBinding;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DataPager.TypedStyles;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.DateNavigator.TypedStyles;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.ExpressionEditor.TypedStyles;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Filtering.TypedStyles;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Flyout.TypedStyles;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.Popups.Calendar.TypedStyles;
using DevExpress.Xpf.Editors.Popups.TypedStyles;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.RangeControl.TypedStyles;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Settings.TypedStyles;
using DevExpress.Xpf.Editors.TypedStyles;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Editors.Validation.TypedStyles;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Xpf.LayoutControl.TypedStyles;
using DevExpress.Xpf.TypedStyles;
using MVVMDemo.EnumItemsSource;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.TypedStyles;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Primitives.TypedStyles;
using System.Windows.Controls.TypedStyles;
using System.Windows.Data;
using System.Windows.Data.TypedStyles;
using System.Windows.Documents;
using System.Windows.Documents.TypedStyles;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Input.TypedStyles;
using System.Windows.Markup;
using System.Windows.Markup.TypedStyles;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Animation.TypedStyles;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Media.TypedStyles;
using System.Windows.Navigation;
using System.Windows.Navigation.TypedStyles;
using System.Windows.Shapes;
using System.Windows.Shapes.TypedStyles;
using System.Windows.Shell;
using System.Windows.TypedStyles;


namespace MVVMDemo.EnumItemsSource {
    
    
    /// <summary>
    /// ListBoxEditView
    /// </summary>
    public partial class ListBoxEditView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\..\Modules\EnumItemsSource\ListBoxEditView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit listBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/MVVMDemo;component/modules/enumitemssource/listboxeditview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Modules\EnumItemsSource\ListBoxEditView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.listBox = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

