using DevExpress.Mvvm;
using DevExpress.Mvvm.DataAnnotations;
using System.ComponentModel;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.POCOViewModels {
    [POCOViewModel(ImplementIDataErrorInfo = true)]
    public class DataErrorInfoViewModel_RuntimeGeneratedCode : DataErrorInfoViewModel, IDataErrorInfo, INotifyPropertyChanged {
        string IDataErrorInfo.Error { 
            get { return string.Empty; } 
        } 
        string IDataErrorInfo.this[string columnName] { 
            get { return IDataErrorInfoHelper.GetErrorText(this, columnName); } 
        } 

        #region properties and commands
        public override string UserName {
            get { return base.UserName; }
            set {
                if(base.UserName == value)
                    return;
                base.UserName = value;
                RaisePropertyChanged("UserName");
            }
        }

        DelegateCommand _RegisterCommand;
        public DelegateCommand RegisterCommand {
            get {
                return _RegisterCommand ?? 
                    (_RegisterCommand = new DelegateCommand(Register, CanRegister));
            }
        }
        #endregion

        #region INotifyPropertyChanged implementation
        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propertyName) {
            var handler = PropertyChanged;
            if(handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}
