using DevExpress.Mvvm;
using System.ComponentModel;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.POCOViewModels {
    public class LoginViewModel_RuntimeGeneratedCode : LoginViewModel, INotifyPropertyChanged {
        public override string UserName {
            get { return base.UserName; }
            set {
                if(base.UserName == value)
                    return;
                base.UserName = value;
                RaisePropertyChanged("UserName");
            }
        }

        public override string Status {
            get { return base.Status; }
            protected set {//VB_MAKE_PUBLIC_SETTER
                if(base.Status == value)
                    return;
                base.Status = value;
                RaisePropertyChanged("Status");
            }
        }

        DelegateCommand _LoginCommand;
        public DelegateCommand LoginCommand {
            get {
                return _LoginCommand ?? 
                    (_LoginCommand = new DelegateCommand(Login, CanLogin));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propertyName) {
            var handler = PropertyChanged;
            if(handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
