using System.ComponentModel;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.POCOViewModels {
    public class PropertiesViewModel_RuntimeGeneratedCode : PropertiesViewModel, INotifyPropertyChanged {
         public override string UserName {
            get { return base.UserName; }
            set {
                if(base.UserName == value)
                    return;
                string oldValue = base.UserName;
                base.UserName = value;
                OnUserNameChanged(oldValue);
                RaisePropertyChanged("UserName");
            }
         }

        public override string ChangedStatus {
            get { return base.ChangedStatus; }
            protected set {//VB_MAKE_PUBLIC_SETTER
                if(base.ChangedStatus == value)
                    return;
                base.UserName = value;
                RaisePropertyChanged("ChangedStatus");
            }
        }

        #region INotifyPropertyChanged implementation
        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propertyName) {
            var handler = PropertyChanged;
            if(handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        } 
        #endregion
    }
}
