using DevExpress.Mvvm;

// This class demonstrates the code that will be generated by the POCO mechanism at runtime

namespace MVVMDemo.POCOViewModels {
    public class ServicesViewModel_RuntimeGeneratedCode : ServicesViewModel, ISupportServices {
        IServiceContainer _ServiceContainer = null;
        IServiceContainer ISupportServices.ServiceContainer {
            get {
                if(_ServiceContainer == null)
                    _ServiceContainer = new ServiceContainer(this);
                return _ServiceContainer;
            }
        }
    }
}
