Imports DevExpress.Xpf.DemoBase
Imports DevExpress.Xpf.Scheduling.VisualData
Imports System.Windows
Imports System.Windows.Controls

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Highlighted/EmployeeWorkScheduleDemoModule.xaml", "ViewModels/Highlighted/EmployeeWorkScheduleDemoViewModel.(cs)", "Themes/EmployeeWorkSchedule.xaml")>
    Public Partial Class EmployeeWorkScheduleDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class

    Public Class TimeRegionTemplateSelector
        Inherits DataTemplateSelector

        Public Property DinnerTemplate As DataTemplate

        Public Property DinnerId As Object

        Public Overrides Function SelectTemplate(ByVal item As Object, ByVal container As DependencyObject) As DataTemplate
            Dim vm = CType(item, TimeRegionViewModel)
            Return If(vm.TimeRegion.Id Is DinnerId, DinnerTemplate, Nothing)
        End Function
    End Class
End Namespace
