Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo

    <NoAutogeneratedCodeFiles, CodeFiles("Modules/Highlighted/PrintingTemplatesDemoModule.xaml", "ViewModels/Highlighted/PrintingTemplatesDemoViewModel.(cs)", "Themes/Ribbon.xaml")>
    Public Partial Class PrintingTemplatesDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
