using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Customization/TimeRegionsDemoModule.xaml",
        "ViewModels/Customization/TimeRegionsDemoViewModel.(cs)")]
    public partial class TimeRegionsDemoModule : SchedulingDemoModule {
        public TimeRegionsDemoModule() {
            InitializeComponent();
        }
    }
}
