using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Customization/TimeRulerDemoModule.xaml",
        "ViewModels/Customization/TimeRulerDemoViewModel.(cs)")]
    public partial class TimeRulerDemoModule : SchedulingDemoModule {
        public TimeRulerDemoModule() {
            InitializeComponent();
        }
    }
}
