using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Scheduling;
using SchedulingDemo.ViewModels;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/Customization/WindowsCustomizationDemoModule.xaml",
        "Modules/Customization/WindowsCustomizationDemoModule.xaml.(cs)",
        "Modules/Customization/CustomWindows/CustomAppointmentWindow.xaml",
        "Modules/Customization/CustomWindows/CustomGotoDateWindow.xaml",
        "Modules/Customization/CustomWindows/CustomTimeRulerWindow.xaml",
        "ViewModels/Customization/WindowsCustomizationDemoViewModel.(cs)",
        "ViewModels/Customization/CustomWindows/CustomTimeRulerWindowViewModel.(cs)")]
    public partial class WindowsCustomizationDemoModule : SchedulingDemoModule {
        public WindowsCustomizationDemoModule() {
            InitializeComponent();
        }
        void OnTimeRulerWindowShowing(object sender, TimeRulerWindowShowingEventArgs e) {
            e.Window.DataContext = new CustomTimeRulerWindowViewModel(e.TimeRuler, this.scheduler.TimeZone);
        }
    }
}
