using DevExpress.Xpf.DemoBase;

namespace TreeMapDemo {
    [CodeFile("Modules/Heatmap/EmptyCells.xaml")]
    [CodeFile("Modules/Heatmap/EmptyCells.xaml.(cs)")]
    [NoAutogeneratedCodeFiles]
    public partial class EmptyCells : TreeMapDemoModule {
        public EmptyCells() {
            InitializeComponent();
            DataContext = DataLoader.CreateDataSet("/Data/SalesPersons.xml");
        }
    }
}
