using DevExpress.Xpf.DemoBase;

namespace TreeMapDemo {
    [CodeFile("Modules/Heatmap/Labels.xaml")]
    [CodeFile("Modules/Heatmap/Labels.xaml.(cs)")]
    [NoAutogeneratedCodeFiles]
    public partial class Labels : TreeMapDemoModule {
        public Labels() {
            InitializeComponent();
            DataContext = DataLoader.CreateDataSet("/Data/BalanceOfTrade.xml");
        }
    }
}
