using DevExpress.Xpf.DemoBase;

namespace TreeMapDemo {
    [CodeFile("Modules/Heatmap/Tooltip.xaml")]
    [CodeFile("Modules/Heatmap/Tooltip.xaml.(cs)")]
    [NoAutogeneratedCodeFiles]
    public partial class Tooltip : TreeMapDemoModule {
        public Tooltip() {
            InitializeComponent();
            DataContext = DataLoader.CreateDataSet("/Data/PerformanceMonitoring.xml");
        }
    }
}
