using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ViewTypes/DayViewDemoModule.xaml",
        "ViewModels/ViewTypes/DayViewDemoViewModel.(cs)",
        "Themes/Ribbon.xaml")]
    public partial class DayViewDemoModule : SchedulingDemoModule {
        public DayViewDemoModule() {
            InitializeComponent();
        }
    }
}
