using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ViewTypes/ListViewDemoModule.xaml",
        "ViewModels/ViewTypes/ListViewDemoViewModel.(cs)",
        "Themes/Ribbon.xaml")]
    public partial class ListViewDemoModule : SchedulingDemoModule {
        public ListViewDemoModule() {
            InitializeComponent();
        }
    }
}
