using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ViewTypes/OneMonthViewDemoModule.xaml",
        "ViewModels/ViewTypes/OneMonthViewDemoViewModel.(cs)",
        "Themes/Ribbon.xaml")]
    public partial class OneMonthViewDemoModule : SchedulingDemoModule {
        public OneMonthViewDemoModule() {
            InitializeComponent();
        }
    }
}
