using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ViewTypes/WeekViewDemoModule.xaml",
        "ViewModels/ViewTypes/WeekViewDemoViewModel.(cs)",
        "Themes/Ribbon.xaml")]
    public partial class WeekViewDemoModule : SchedulingDemoModule {
        public WeekViewDemoModule() {
            InitializeComponent();
        }
    }
}
