using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/ViewTypes/WorkWeekViewDemoModule.xaml",
        "ViewModels/ViewTypes/WorkWeekViewDemoViewModel.(cs)",
        "Themes/Ribbon.xaml")]
    public partial class WorkWeekViewDemoModule : SchedulingDemoModule {
        public WorkWeekViewDemoModule() {
            InitializeComponent();
        }
    }
}
